// All reusable variables here
#let myLang = "en"
#let myName = "Marco Bellò"
#let myID = "2122196"
#let myTitle = "Crossdem:"
#let myTitle2 = "TODO"
#let myDegree = "Master Thesis in Computer Science"
#let myUni = "University of Padova"
#let myDepartment = "Department of Mathematics ''Tullio Levi-Civita''"
#let myFaculty = "Master Degree in Computer Science"
#let profTitle = "Prof. "
#let myProf = "Alessandro Galeazzi"
#let myTutor = "Nome Cognome"
#let myLocation = "Padova"
#let myAA = "2026-2027"
#let myTime = "December 2026"