#counter(page).update(1)
= Introduction <cap:intro>

== Overview <sec:iot_overview>
From the first computational machines introduced in the mid-20th century to the present day, the evolution of computer science has been characterized by continuous innovation and rapid technological advancement. The advent of the Internet toward the end of the century profoundly transformed our interaction with technology, reshaping social interactions, economic forces, political dynamics and the way we access and share information.

In recent decades, one of the most significant developments in this field has been the emergence of the Internet of Things (IoT) paradigm. This concept envisions a world where everyday objects, ranging from healthcare sensors and industrial actuators to home appliances, are interconnected enabling them to collect and exchange data. 
This connectivity facilitates a wide array of applications that enhance daily life through automation, remote sensing and control. Since its introduction, IoT has experienced an exponential growth and widespread adoption across various sectors, from smart homes to industrial automation, healthcare, agriculture, disaster recovery and many others. 

The history of IoT started way back in 1982 when a vending machine was connected to the internet and set to display the number of bottles with its temperature. A decade later, in 1991, Mark Weiser introduced the concept of ubiquitous computing @ubiquitosus_computing, which was just a theoretical expression of what IoT is today. The first accepted technology used in this field was the Radio Frequency Identification (RFID) in 1998, a wireless technology using radio waves to automatically identify and track tags attached to objects. Exactly from here, Kevin Ashton, at the time executive director of the Auto-ID center at the MIT, in 1999 @ashton2009internet during a speech about the new idea of using RFID in the P&G's supply chain, coined the term "Internet of Things".
The Auto-ID center was a collaboration between industries and private sectors, holding 60 researchers and 15 professional leading research networks in IoT. The first conference on IoT was organized and held in 2008 and from there many countries embraced it and drafted action plans on the IoT. Later, in 2014, Auto-ID lab released a state-of-the-art report on IoT @auto-id-lab.

At the beginning, there has still been skepticism about embracing IoT until when tech giants that made IoT big business opportunities. Various report projected that 25 billion devices were connected before 2020 @fehske2011global, increasing to 38 billion by the end of 2025 and 50 billion by the end of 2030 @chui2021internet. According to a market research estimate, the global IoT industry was worth 245 billion dollars in 2020 and is predicted to grow to 8,131 billions by 2030 @al2020internet. 

Nowadays, IoT environments are characterized by the presence of a large number of heterogeneous and resource constrained devices, in terms of memory, CPU, bandwidth or battery and often are massively deployed in areas of interest to enable IoT applications.  
However, they may be used in contexts where the communication is over error-prone and lossy radio channels. Due to their inherent and limited characteristics, IoT devices may experience various network performance problems, especially when deployed in hostile environments (e.g. war zones, agricultural fields, disastered zones ecc.), or suffer from excessive energy consumption resulting from network congestions. 
These challenges have driven the development and standardization of a wide range of different protocols and frameworks for management for constrained devices and networks. 
This includes a stack of communication solutions designed to optimize resources at various levels. From wireless communication technologies like Zigbee @zigbee, Bluetooth Low Energy (BLE) @ble, LoraWAN, Sigfox and NB-IoT @lpwan_overview for Low-Power Wide-Area Networks (LPWAN), to network-layer solutions such as 6LowPAN @6lowpan and RPL @rpl that enable efficient IPv6 routing over lossy channels. At the application level, we can find lightweight messaging protocols like MQTT and CoAP @mqtt_coap , which have become essential for reliable data exchange in resource-constrained environments. Furthermore, there are also specialized management interfaces such as LWM2M or XMPP @l2m2m_xmpp, introduced to manage the remote configuration and monitoring of these devices. 

This massive expansion of the IoT ecosystem has been further accelerated by the development with other innovative technologies. In particular, the introduction of the 5G cellular network technology @5G_iot_survey fulfill the needs of complex IoT architectures providing the high data rate and low latency required for real-time data transmission. Moreover, the new promising 6G network technology will further push the boundaries of IoT applications towards the so called Internet of Everything (IoE), including not only devices but also also people, processes and data, leveraging the integration of AI and machine learning @6G_survey.
On the other hand, the emerging and consolidated solutions offered by cloud computing, have enabled to store and process huge amounts of information generated by billions of devices. Furthermore, the integration of edge computing has enabled data processing closer to the source, reducing bandwidth and improving response times. 

Another critical aspect of IoT regards security, which includes all strategies of protecting digital resources such as systems, networks, data and devices against attacks from malicious and unauthorized users that may cause threats, damage or disruption.
However, IoT networks are based on low-power and lossy networks where devices are constrained by energy, processing power and memory, as mentioned earlier. This brings different security challenges that cannot be addressed by traditional security mechanisms for classical wireless networks because are unsuitable or too resource-demanding. Consequently, appropriate encryption schemes are leveraged for ensuring the security of the IoT environment.

Moreover, IoT data may deal with sensitive or life critical data, such as in healthcare or industrial applications and this makes it even more challenging to ensure compliance with ethical issues, security laws and policies @iot_privacy.

On the othen hand, IoT architectures must meet important security requirements. These are defined by the well-known CIA triad, which stands for Confidentiality, Integrity and Availability. In this context, confidentiality ensures that sensitive information is accessible only to authorized entities, preventing unauthorized access and data breaches. Integrity guarantees that the data remains accurate and unaltered during transmission and storage, protecting against tampering or corruption. Availability ensures that services and data are accessible when needed, minimizing downtime.

In addition to these core principles, authentication and non-repudiation mechanisms are also crucial. Authentication verifies the identity of devices and users, ensuring that only legitimate entities can access the network. Non repudiation provides proof of the origin and integrity of data, preventing entities from denying their actions.
Together, all these security measures form a protected framework to safeguard IoT systems against various threats and vulnerabilities. 

== Problem statement <sec:problem_statement>
As seen in the previous section, the IoT faces unique challenges inherent to its nature. These include a massive number of connected devices, heterogeneity in communication protocols, deployment in hostile or lossy environments, resource limitations and stringent security and privacy requirements. These factors render IoT ecosystems significantly more complex than traditional networks.

The proliferation of diverse communication protocols has led to a fragmented ecosystem where devices often communicate using incompatible standards. Given that a convergence toward a single global standard is unlikely @iot_interoperability @iot_interoperability2 and therefore solutions enabling interoperability are essential.

Interoperability, in a broad sense, refers to the capability of interconnecting heterogeneous platforms, systems and services to fully cooperate with each other in every aspect of their operations. The goal is to achieve seamless interaction, such as turning on/off or exchanging sensor data, regardless of the underlying technologies.

This can be achieved by working on the various layers of the IoT protocol stack, better explained in @sec:iot_architecture, from the perception layer to the application layer. In particular, we have to focus on the middleware layer in the stack if we want to achieve interoperability, as it includes protocols such as CoAP and MQTT. While this remains an active area of research, if we look at the literature, we can find a multitude of various approaches attempting to address these integration challenges. For instance, in @broker_extension @nwankwo2024integration @sumadi2021enabling, the authors propose an extension or a translator to bridge the gap between publish-subscribe and request-response architectures of MQTT and CoAP protocols. On the other hand, other studies focus on more general and agnostic frameworks. Solutions such as those proposed in @multi_protocol_iot and @multi_protocol_iot_bridge, as well as in @7908961 and @8767248, attempt to build multi-protocol gateways capable of handling a broader range of standards simultaneously.

This great variety of solutions highlights the complexity of the problem. While the literature offers numerous strategies, general-purpose approaches that aim for high abstraction frequently encounter constraints and performance trade-offs, especially when applied to real-world scenarios. Therefore, to overcome these limitations, a detailed preliminary analysis and a tailored integration designed around the specific use case are essential.

As mentioned earlier, because of this heterogeneity, we must face security challenges. Hence, it is important to ensure the safety of the system against potential malicious actors. In the context of smart agriculture, the absence of appropriate security measures can lead to serious consequences. For instance, unauthorized access to actuators, such as irrigation valves or ventilation systems, could allow an attacker to alter critical environmental parameters, directly affecting crop health and yield. Without data encryption, telemetry streams carrying sensor readings such as temperature or humidity are exposed to interception and manipulation. Moreover, agricultural data often carries commercial value, and its unauthorized disclosure can cause financial losses to the operator. Finally, the lack of authentication makes the system vulnerable to unauthorized access, data injection and message eavesdropping. Furthermore, without rate limiting policies, a malicious client can flood the broker with a large volume of requests, causing a denial of service. A deeper analysis of the security risks affecting IoT systems at each layer of the protocol stack is provided in @sec:iot_security. For these reasons appropriate security mechanisms  must be implemented for the mentioned protocols to ensure data encryption, authentication and authorization, as well as fine-grained permission assessment, all while maintaining a balance with system performance and usability.

This work focuses specifically on the interoperability and security requirements between MQTT and CoAP protocols within the context of smart agriculture, particularly for smart greenhouse data collection and control. These elements are useful for monitoring conditions and optimizing crop yield through data insights. The specific requirements and constraints of the architecture will be detailed and analyzed in the following sections.


== Goals <sec:goals>
In this project, conducted under the guidance of Sandro Lain at M31 S.r.l., the primary objective is to study, design and implement a solution for the seamless integration of heterogeneous IoT protocols. The research focuses specifically on MQTT and CoAP, two of the most widely adopted standards in the IoT landscape. As will be detailed in the following sections, the former relies on a publish-subscribe architecture, while the latter is built upon a request-response model. Because of this fundamental difference, their integration is not trivial and requires a deep understanding of their respective characteristics.

The proposed solution is applied to a smart agriculture use case, specifically for smart greenhouse scenarios. In this environment, a variety of sensors and actuators are deployed to perform telemetry and data collection. This information must be transmitted to a central database for analytics and processing. Furthermore, the system should be designed to handle downward communication, enabling both manual user control over actuators and autonomous actions triggered by specific conditions.

In addition to the architectural challenges, the design process is guided by some operational requirements, discussed more in detail in @sec:arch_requirements, for thinking towards a production grade product:

- Multi-tenancy and Data Isolation: the system must support multiple independent tenants and ensuring data streams and devices remain isolated and secure.

- Open Source Solutions: the architecture must be built using open-source technologies and frameworks to promote transparency and avoid costs and vendor lock-in.

- High Availability (HA): the architecture should consider redundancies for services to prevent single points of failure for resilient operation.

- Identity Access Management (IAM): the system must provide a set of policies and group-based permissions for access control, both for users and devices.

- Machine-to-Machine (M2M) Authentication: where possible, the system should consider M2M authentication to ensure trusted communication between system components, such as devices and backend services.

- Interoperability: the system must ensure seamless communication and data exchange between MQTT and CoAP devices, considering future extensibility to other protocols. This includes the ability to translate between the different communication paradigms, abstracting protocol differences while maintaining performance and reliability.  \

Finally, a requirement of the system is to provide security mechanisms, adhering to the CIAA principles (Confidentiality, Integrity, Availability and Authentication). Given the resource-constrained nature of IoT devices and the different authentication mechanisms inherent to MQTT and CoAP, the implementation of appropriate security protocols is essential. Regarding users, as admins, operators or maintainers accessing the system, it is important to establish authentication and authorization access controls.


== Structure of the thesis <sec:structure_of_the_thesis>
The rest of the thesis is organized as follows:

In #link(<cap:background>, "Chapter 2") we provide the necessary background knowledge on IoT characteristics, architectures and layers, as well a panorama of the most relevant communication protocols and enabling technologies, with a focus on MQTT and CoAP description. Finally, we analyze the security requirements, challenges and threats and the most common security mechanisms for IoT systems.

In #link(<cap:methodology>,"Chapter 3") we describe the methodology adopted for the design and implementation of the solution, including the architectural design and requirements, a well defined use case scenario for smart agriculture, the implementation details of the MQTT and CoAP integration and the challenges encountered during the development process.\

In #link(<cap:future_directions>, "Chapter 4") we discuss potential future directions for the development and enhancement of the multi-protocol communication framework, including post-quantum security for IoT, firmware update mechanisms for IoT devices, M2M authentication, physical isolation and other integrations. 

Finally, in #link(<cap:conclusion>, "Chapter 5") we present a summary of the result obtained from the study, design and implementation of the solution, along with a brief discussion.
