#pagebreak(to:"odd")
= Conclusions <cap:conclusion>

The continuous evolution of the Internet of Things and its rapid expansion into numerous domains have driven the proliferation of a wide variety of devices, protocols and technologies. As discussed throughout this work, all solutions in this space share a common requirement: ensuring long battery life, since many IoT devices must operate for extended periods without the possibility of recharging or replacement. This requirement, often combined with potentially unfavorable network conditions, shapes all subsequent technological choices, from communication protocols to network architectures, down to the design of the devices themselves.

This heterogeneity has, on one hand, enabled the needs of highly diverse sectors to be met through flexibility and adaptability to specific application scenarios. On the other hand, it has produced a fragmentation into several technologies that are often poorly interoperable with one another, making communication across different standards particularly difficult, especially at the application layer.
Developing an interoperability framework that allows devices and applications to communicate effectively, regardless of the underlying protocols or technologies, is a critical challenge that raises numerous problems and demands careful design decisions. However, adopting a holistic approach that considers the entire IoT ecosystem while accounting for the specific needs of every sector is practically infeasible and potentially counterproductive, as it risks producing solutions that are too generic to be efficient in any particular context.
For this reason, a more targeted approach is preferable, one that focuses on well-defined use cases and develops interoperability solutions suited to their requirements. In this work, we focused on the agricultural sector, which represents an area of significant interest and potential for IoT, with particular attention to smart greenhouses, though the proposed framework is extensible to other scenarios such as open-field precision agriculture. As described, it was necessary from the earliest stages to define clear boundaries for the framework, taking into account the needs of different actors, including administrators, maintainers and operators, and ensuring that the system could support communication among heterogeneous devices while remaining scalable and adaptable to different technologies and protocols. This also carries important implications for security, which is an imperative concern for any IoT solution, but one that in this context requires particular attention given the critical nature of the problem. Based on the specific use case, we designed a custom authorization and authentication model that accounts for the relationships of the involved actors and that ensures controlled and secure access to resources and data.

Providing an interoperability framework that guarantees the security of data and communications, and that is capable of protecting devices from attacks and vulnerabilities, was a complex challenge that required considerable care. It occasionally demanded solutions that were not entirely elegant or that involved trade-offs in terms of efficiency and simplicity, but which were nonetheless necessary. The requirement to rely exclusively on open-source services introduced an additional constraint that made it harder to identify suitable solutions, yet it guarantees full control over the implementation at the cost of self-management.
The challenge proved particularly interesting because we chose to bridge two communication protocols that sit at opposite ends of the communication paradigm spectrum: MQTT and CoAP. As discussed, several difficulties emerged during the implementation phase, even after careful preliminary study. What initially appeared suitable for integration based on a high-level analysis later clashed with technical limitations, such as the constraints imposed by relying on a single centralized message broker. This led to the adoption of alternative solutions, separating the two protocols and introducing specific services built to mediate between them. Additional requirements, such as supporting high availability and multi-tenancy, further increased the overall complexity and influenced the final design choices.
As future work, it would be valuable to extend the framework with support for post-quantum secure communication, a problem that is already gaining urgency today and will become more relevant in the coming years. In addition, a production deployment must account for firmware updates, which represent a specific challenge given the inherent constraints of IoT devices. Finally, service-to-service authentication is a further aspect of considerable relevance that deserves dedicated attention.

In conclusion, this work demonstrates that building a practical interoperability framework for heterogeneous IoT environments is achievable, provided that the scope is carefully defined and the design choices are grounded in the concrete requirements of the target domain. The framework developed here, while tailored to smart greenhouse scenarios, establishes a foundation that can be adapted and extended as the IoT landscape continues to evolve. The lessons learned throughout this process, both from the successes and the compromises made along the way, offer useful guidance for future efforts in this space.