# Setup

In [1]:
from datetime import date, datetime
from urllib.parse import urljoin
from bs4 import BeautifulSoup
from pathlib import Path
from time import sleep
import subprocess
import requests
import pandas
import spacy
import glob
import time
import json
import csv
import re
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath("__file__")))  # go to ~/crossdem/ by jumping up twice
DATA_DIR = os.path.join(BASE_DIR, "datasets")
PMS_DIR = os.path.join(DATA_DIR, "prime_ministers")
VALIDATION_DIR = os.path.join(DATA_DIR, "prime_ministers_validation")
IMGS_DIR = os.path.join(os.getcwd(), "imgs")

os.makedirs(IMGS_DIR, exist_ok=True)

# De Gasperi was not scraped, a dataset with all speeches was taken from https://github.com/StefanoMenini/De-Gasperi-s-Corpus/
#degasperi_df = pandas.read_csv(f"{DATA_DIR}/degasperi/degasperi_speeches.csv")

POL_INFO = {
    "degasperi":   {"leaning": "C",  "color": "#2f4f4f"},  # dark slate grey — PM from 1945
    "fanfani":     {"leaning": "CL", "color": "#e6194B"},  # red — 1954
    #"scelba":      {"leaning": "CR", "color": "#8b4513"},  # saddle brown — 1954 (no data)
    #"segni":       {"leaning": "CR", "color": "#1e90ff"},  # dodger blue — 1955 (no data)
    "leone":       {"leaning": "C",  "color": "#ff4500"},  # orange-red — 1963
    #"moro":        {"leaning": "CL", "color": "#556b2f"},  # dark olive green — 1963 (no data)
    "rumor":       {"leaning": "C",  "color": "#7f0067"},  # deep magenta/plum — 1968
    "colombo":     {"leaning": "C",  "color": "#008080"},  # dark teal — 1970
    "andreotti":   {"leaning": "CR", "color": "#c00000"},  # bright crimson — 1972
    "cossiga":     {"leaning": "CR", "color": "#e6beff"},  # light violet — 1979
    "forlani":     {"leaning": "CR", "color": "#ffe119"},  # yellow — 1980
    "spadolini":   {"leaning": "C",  "color": "#a9a9a9"},  # grey — 1981
    "craxi":       {"leaning": "CL", "color": "#ffd8b1"},  # apricot — 1983
    "goria":       {"leaning": "C",  "color": "#000075"},  # navy — 1987
    "demita":     {"leaning": "CL", "color": "#808000"},  # olive — 1988
    "amato":       {"leaning": "L",  "color": "#aaffc3"},  # mint — 1992
    "ciampi":      {"leaning": "C",  "color": "#9A6324"},  # brown — 1993
    "berlusconi":  {"leaning": "R",  "color": "#800000"},  # dark red / maroon — 1994
    "dini":        {"leaning": "CL", "color": "#fabed4"},  # pink — 1995
    "prodi":       {"leaning": "CL", "color": "#469990"},  # teal — 1996
    "dalema":     {"leaning": "L",  "color": "#dcbeff"},  # lavender — 1998
    "monti":       {"leaning": "CR", "color": "#bfef45"},  # lime — 2011
    "letta":       {"leaning": "L",  "color": "#f032e6"},  # magenta — 2013
    "renzi":       {"leaning": "CL", "color": "#42d4f4"},  # cyan — 2014
    "gentiloni":   {"leaning": "CL", "color": "#911eb4"},  # purple — 2016
    "conte":       {"leaning": "CL", "color": "#f58231"},  # orange — 2018
    "draghi":      {"leaning": "C",  "color": "#3cb44b"},  # green — 2021
    "meloni":      {"leaning": "R",  "color": "#4363d8"},  # blue — 2022
}

DISPLAY_NAME_OVERRIDES = {
    "dalema": "D'Alema",
    "demita": "De Mita",
    "degasperi": "De Gasperi"
}

def display_name(pol):
    return DISPLAY_NAME_OVERRIDES.get(pol, pol.capitalize())

CHECK_INTEGRITY = False

# backward compatibility
#POLITICIANS = [
#    pol for pol in POL_INFO
#    if pol != "degasperi" and pol not in ("moro", "segni", "scelba")
#]
#POL_COLORS = {pol: info["color"] for pol, info in POL_INFO.items()}
#POL_LEANING = {pol: info["leaning"] for pol, info in POL_INFO.items()}

#politicians_dfs = {
#    "degasperi": degasperi_df
#}

#for pol in politicians:
#    speeches = glob.glob(f"{DATA_DIR}/{pol}/csv_out/*.csv")
#    pol_df = pandas.concat([pandas.read_csv(f, nrows=1) for f in speeches], ignore_index=True)
#    politicians_dfs[pol] = pol_df

politicians_dfs = {}
# csv faster for smaller datasets (eg 1 row)
def read_single_row(path):
    with open(path, newline="", encoding="utf-8") as f:
        return next(csv.DictReader(f))

for pol in POL_INFO:
    speeches = glob.glob(f"{PMS_DIR}/{pol}/csv_out/*.csv")
    rows = [read_single_row(f) for f in speeches]
    if pol == "degasperi":
        df1 = pandas.read_csv(f"{PMS_DIR}/degasperi/degasperi_speeches.csv")
        df2 = pandas.read_csv(f"{VALIDATION_DIR}/degasperi/degasperi_validation.csv")
        politicians_dfs[pol] = pandas.concat([df1, df2])
    elif pol == "meloni":
        df1 = pandas.DataFrame(rows)
        df2 = pandas.read_csv(f"{VALIDATION_DIR}/meloni/meloni_validation.csv")
        politicians_dfs[pol] = pandas.concat([df1, df2])
    else:
        politicians_dfs[pol] = pandas.DataFrame(rows)
#print(politicians_dfs["conte"])
politicians_dfs["meloni"].head()

,politician,historical_date,location,title,url,audio_file,text,tags,description,hate_speech,negativity,aggressiveness,target
0,meloni,2000-10-16,ROMA,"""Convegno di Destra Protagonista a Roma"" org. ...",https://www.radioradicale.it/scheda/124586/con...,crossdem/datasets/meloni/audio_out/124586_melo...,"Ci sia una vittoria, una vittoria netta, una v...",NaN,NaN,NaN,NaN,NaN,NaN
1,meloni,2000-11-22,ROMA,Incontro tra gli studenti del Liceo Torquato T...,https://www.radioradicale.it/scheda/133778/inc...,crossdem/datasets/meloni/audio_out/133778_melo...,"di richiesto e di chiarimento che voglio fare,...",NaN,NaN,NaN,NaN,NaN,NaN
2,meloni,2001-12-19,ROMA,Stati Generali dell'Istruzione (presso il Pala...,https://www.radioradicale.it/scheda/134365/sta...,crossdem/datasets/meloni/audio_out/134365_melo...,caratteristiche delle verifiche nazionali già ...,NaN,NaN,NaN,NaN,NaN,NaN
3,meloni,2000-12-16,VERONA,"""Quid est Veritas? Verità, cultura, testo scol...",https://www.radioradicale.it/scheda/135795/qui...,crossdem/datasets/meloni/audio_out/135795_melo...,è quello di inventare un'autorità che tuteli e...,NaN,NaN,NaN,NaN,NaN,NaN
4,meloni,2002-02-16,ROMA,Convention di Destra protagonista componente ...,https://www.radioradicale.it/scheda/136073/con...,crossdem/datasets/meloni/audio_out/136073_melo...,coordinatrice del Comitato per il mondo giovan...,NaN,NaN,NaN,NaN,NaN,NaN


# Measure of Textual Lexical Diversity


## Number of tokens per PM
> Measures the amount of collected data


In [ ]:

# --- Helper function ---
def speech_stats(df, name):
    # Date range
    dates = pandas.to_datetime(df["historical_date"], format="%Y-%m-%d", errors="coerce")    
    oldest = dates.min()
    newest = dates.max()

    # Median word count
    word_counts = df["text"].dropna().str.split().str.len()
    median_wc = word_counts.median()

    print(f"=== {name} ===")
    print(f"  Date range : {oldest.date()} → {newest.date()}")
    print(f"  Speeches   : {len(df)}")
    print(f"  Median words/speech: {median_wc:.0f}")
    print()

for pol, df in politicians_dfs.items():
    #print(pol)
    #print(df)
    speech_stats(df, pol)

In [6]:
import spacy

# Load Italian model if your speeches are in Italian, otherwise use en_core_web_sm
# pip install spacy && python3 -m spacy download it_core_news_sm
nlp = spacy.load("it_core_news_sm")


In [7]:

# Disable unneeded pipeline components for speed — we only need tokenization
nlp.select_pipes(enable=[])  # disables everything except tokenizer

def count_tokens(text):
    if pandas.isna(text) or not isinstance(text, str):
        return 0
    return len(nlp(text))

summaries = []
for pol, df in politicians_dfs.items():
    speech_stats(df, pol)
    df["token_count"] = df["text"].apply(count_tokens)
    summary = (
        df.assign(politician=pol)
        .groupby("politician")["token_count"]
        .agg(total_tokens="sum", speech_count="count", avg_tokens_per_speech="mean")
        .reset_index()
    )
    summaries.append(summary)

token_summary = pandas.concat(summaries, ignore_index=True)
print(token_summary)

print(f"\nTotal tokens across all politicians: {token_summary['total_tokens'].sum()}")
print(f"Total speeches across all politicians: {token_summary['speech_count'].sum()}")

=== degasperi ===
  Date range : 1901-09-21 → 1954-07-24
  Speeches   : 473
  Median words/speech: 701

=== fanfani ===
  Date range : 1962-03-22 → 1993-07-25
  Speeches   : 21
  Median words/speech: 774

=== leone ===
  Date range : 1987-04-02 → 2007-09-09
  Speeches   : 8
  Median words/speech: 886

=== rumor ===
  Date range : 1986-09-03 → 1989-02-20
  Speeches   : 5
  Median words/speech: 1880

=== colombo ===
  Date range : 1984-05-23 → 1984-05-23
  Speeches   : 1
  Median words/speech: 3031

=== andreotti ===
  Date range : 1978-04-04 → 2009-05-11
  Speeches   : 400
  Median words/speech: 1926

=== cossiga ===
  Date range : 1977-04-21 → 2009-06-11
  Speeches   : 225
  Median words/speech: 2014

=== forlani ===
  Date range : 1985-12-01 → 2015-02-05
  Speeches   : 75
  Median words/speech: 1718

=== spadolini ===
  Date range : 1981-12-14 → 1994-04-22
  Speeches   : 105
  Median words/speech: 1698

=== craxi ===
  Date range : 1980-06-06 → 2005-09-17
  Speeches   : 114
  Median w

## Check Data Integrity: N-Gram Centroid
Is there some way to check whether a series of texts are written by the same person eg they have the same style?
Oss: vectorize speeches, not words.

Internal consistency check using **3-5 grams** to capture morphology and style. 
For each politician:
1. Vectorize all speeches
2. For each speech compute centroid of all other speeches
3. Compute cosine distance between speech and centroid
4. All speeches "too far away" are flagged as outliers 

Vectorizer fit per-politician. We don't want to filter out stop-words and similar. We care about *style*, not *content*.

Flags bottom 10% of each politician (ie the bottom 10% of speeches with less similarity with all the rest). similarity intended as cosine distance, meaning the angle between a speech and the average of all the others.

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd


def extract_speech_id(audio_path):
    match = re.search(r'/(\d+)_', audio_path)
    return int(match.group(1)) if match else None

def flag_outliers(politicians_dfs: dict, flag_percentile=10, min_speeches=3):
    records = []
    skipped = []

    for pol, df in politicians_dfs.items():
        sub = df.dropna(subset=["text"]).copy()
        sub = sub[sub["text"].astype(str).str.strip() != ""]

        if len(sub) < min_speeches:
            skipped.append((pol, f"only {len(sub)} usable speeches, need >= {min_speeches}"))
            continue

        texts = sub["text"].astype(str).tolist()

        if "audio_file" in sub.columns:
            ids = sub["audio_file"].apply(extract_speech_id).tolist()
        else:
            ids = sub.index.tolist()  # fallback, e.g. for degasperi

        vec = TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5), min_df=1)
        X = vec.fit_transform(texts)
        n = X.shape[0]

        for i in range(n):
            mask = np.ones(n, dtype=bool)
            mask[i] = False
            centroid = np.asarray(X[mask].mean(axis=0))
            sim = cosine_similarity(X[i], centroid)[0, 0]
            records.append({
                "politician": pol,
                "speech_id": ids[i],
                "n_chars": len(texts[i]),
                "self_sim": sim,
            })

    if skipped:
        print("Skipped politicians (not enough data):")
        for pol, reason in skipped:
            print(f"  - {pol}: {reason}")

    df_out = pd.DataFrame(records)
    if df_out.empty:
        return df_out

    # any value under the threshold is below the cutoff percentile
    df_out["threshold"] = df_out.groupby("politician")["self_sim"].transform(
        lambda s: np.percentile(s, flag_percentile)
    )
    df_out["is_outlier"] = df_out["self_sim"] < df_out["threshold"]

    return df_out.sort_values("self_sim")


if CHECK_INTEGRITY:
    results = flag_outliers(politicians_dfs, flag_percentile=10)
    results[results["is_outlier"]]

    # --- 1. Export outliers (percentile-based, for manual review) to CSV ---
    outliers = results[results["is_outlier"]].copy()
    outliers.to_csv("outlier_speeches.csv", index=False)
    print(f"Exported {len(outliers)} flagged speeches to outlier_speeches.csv")

    # --- 2. Human-readable per-politician quality summary (absolute threshold) ---
    ABS_THRESHOLD = 0.5

    summary = (
        results.groupby("politician")
        .agg(
            n_speeches=("self_sim", "size"),
            n_low_confidence=("self_sim", lambda s: (s < ABS_THRESHOLD).sum()),
            mean_self_sim=("self_sim", "mean"),
            min_self_sim=("self_sim", "min"),
        )
    )
    summary["pct_correct"] = 100 * (1 - summary["n_low_confidence"] / summary["n_speeches"])
    summary = summary.sort_values("pct_correct")

    for pol, row in summary.iterrows():
        print(f"{display_name(pol)}: correct at {row['pct_correct']:.1f}% "
            f"({int(row['n_low_confidence'])}/{int(row['n_speeches'])} below threshold, "
            f"mean sim={row['mean_self_sim']:.2f})")

### Problems
same politician, different speech_ids, different n_chars, but exactly identical self_sim to 15 decimal places:

- cossiga: 0.14699581356744493 appears for 10 different speech_ids (44388, 107647, 116156, 116242, 144319, 157846, 206103, 105433, 129584, 144326), with wildly different lengths (161 to 1160 chars).
  - "Sottotitoli a cura di QTSS"
- berlusconi: 0.07913934889895312 appears for 7 different speech_ids (129585, 165008, 112642, 390627, 163004, 75146, 24271).
- d'alema: 0.06369136954541513 appears for 7 different speech_ids (116242, 143895, 157908, 124913, 146104, 105561, 107312).
  -   - "Sottotitoli a cura di QTSS"
- letta: 0.05826582103963773 appears for 5 different speech_ids.
- craxi: 0.016491752222592037 for 2 speech_ids, 0.1752161444907769 for 4 more.
Smaller versions of the same pattern in amato, prodi, ciampi, spad

> Some speeches are filled with "Sottotitoli a cura di QTSS" repeated an arbitrary amount of times.

----------------------
straightforward broken scrapes/transcriptions, independent of the clustering issue above:

- forlani 39460 — 39 chars, self_sim 0.004
  - "Ciao Ciao Ciao Ciao Ciao Ciao Ciao Ciao"
- ciampi 116242 — 26 chars, self_sim 0.093 (shortest speech in the whole dataset)
- andreotti 23204 — 53 chars, self_sim 0.066
- berlusconi 317479 — 43 chars, self_sim 0.102
Several other sub-300-char entries across craxi, prodi, andreotti, spadolini

---------------------------
Total speeches: 5,596
Total flagged as outliers: 567 (~10.1%) — but remember, this percentage is built into the method (10th percentile per politician), so "10%" doesn't tell you anything about actual data quality. It would show 567 flagged even on a perfectly clean corpus.
Speeches that look like genuine errors (near-zero self_sim + very short n_chars, or part of the identical-score duplicate clusters): roughly 40-50 rows by my count above.

So yes — 40-50 out of 5,596 is under 1% in aggregate

### Human-Readable Results
```bash
Skipped politicians (not enough data):
  - colombo: only 1 usable speeches, need >= 3
  - gentiloni: only 1 usable speeches, need >= 3
Exported 567 flagged speeches to outlier_speeches.csv
Conte: correct at 80.0% (6/30 below threshold, mean sim=0.61)
Goria: correct at 81.1% (7/37 below threshold, mean sim=0.76)
Craxi: correct at 82.5% (17/97 below threshold, mean sim=0.69)
Leone: correct at 83.3% (1/6 below threshold, mean sim=0.63)
Degasperi: correct at 86.7% (63/473 below threshold, mean sim=0.67)
Cossiga: correct at 88.2% (21/178 below threshold, mean sim=0.73)
Ciampi: correct at 90.4% (7/73 below threshold, mean sim=0.73)
Spadolini: correct at 91.8% (8/97 below threshold, mean sim=0.75)
Forlani: correct at 92.3% (5/65 below threshold, mean sim=0.75)
Draghi: correct at 92.3% (2/26 below threshold, mean sim=0.85)
Meloni: correct at 92.5% (15/199 below threshold, mean sim=0.73)
Prodi: correct at 92.6% (38/515 below threshold, mean sim=0.80)
Berlusconi: correct at 92.9% (38/535 below threshold, mean sim=0.80)
Dini: correct at 92.9% (22/310 below threshold, mean sim=0.71)
Andreotti: correct at 93.6% (21/327 below threshold, mean sim=0.80)
Renzi: correct at 95.1% (7/143 below threshold, mean sim=0.79)
Fanfani: correct at 95.2% (1/21 below threshold, mean sim=0.70)
Amato: correct at 96.0% (29/722 below threshold, mean sim=0.82)
D'Alema: correct at 96.1% (32/829 below threshold, mean sim=0.84)
De Mita: correct at 96.2% (6/157 below threshold, mean sim=0.83)
Letta: correct at 96.3% (19/509 below threshold, mean sim=0.80)
Monti: correct at 97.9% (5/240 below threshold, mean sim=0.83)
Rumor: correct at 100.0% (0/4 below threshold, mean sim=0.89)
```

### Idea

Just cut anything under `self_sim<0.15`


## MTLD Measure of Textual Lexical Diversity
> Measures lexical diversity

By sequentially evaluating the Type-Token Ratio (TTR) across segments, MTLD avoids the common problem of shorter texts artificially inflating lexical diversity 


In [2]:
from lexicalrichness import LexicalRichness

def compute_mtld(text):
    lex = LexicalRichness(text)
    # Need at least a few tokens for a meaningful MTLD
    if lex.words < 10:
        return None
    return lex.mtld(threshold=0.72)


summaries = []
for pol, df in politicians_dfs.items():
    #speech_stats(df, pol)
    df["mtld"] = df["text"].apply(compute_mtld)
    summary = (
        df.assign(politician=pol)
        .groupby("politician")["mtld"]
        .agg(
            avg_mtld="mean",
            median_mtld="median",
            speech_count="count"
        )
        .reset_index()
    )
    summaries.append(summary)


token_summary = pandas.concat(summaries, ignore_index=True)
print(token_summary)

    politician    avg_mtld  median_mtld  speech_count
0    degasperi  141.829723   137.642465           473
1      fanfani  111.910603   119.225097            21
2        leone   98.124496   103.323466             7
3        rumor  126.318967   129.298646             4
4      colombo  156.410815   156.410815             1
5    andreotti  111.120911   111.189813           400
6      cossiga   82.482046    85.891544           225
7      forlani   98.046834   103.330140            74
8    spadolini  110.089729   115.080622           105
9        craxi   90.521601    91.846608           112
10       goria  108.469053   111.156935            42
11      demita   90.661349    92.115003           208
12       amato   96.032235    96.025639           901
13      ciampi  113.600597   109.393879            71
14  berlusconi   90.836417    92.534970           534
15        dini  108.670262   106.194803           310
16       prodi   93.341206    94.921585           515
17      dalema   92.956690  

### Plotly Dynamically Choosing Politicians

In [10]:
import plotly.graph_objects as go
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display
import numpy as np

PALETTE = px.colors.qualitative.Dark24
MAX_DOC_NUM = 50
PLOT_HEIGHT = 800

DOWNLOAD_CONFIG = {
    "toImageButtonOptions": {
        "format": "png", 
        "filename": "mtld_pms", 
        "scale": 3
        }
    }

# NO one equal one
# median among all speeches, not among medians of single PMs
GLOBAL_MTLD_MEDIAN = pandas.concat(
    [df["mtld"].dropna() for df in politicians_dfs.values()]
).median()

# --- config for the career-percentage line view ---
DATE_COL = "historical_date"         
CAREER_STEPS = 100          # resolution of the x-axis (0..100%)
CAREER_WINDOW_PCT = 4        # a step aggregates speeches within +/- this many percentage points

MARKER_MIN_SIZE = 2
MARKER_MAX_SIZE = 16

def scaled_marker_sizes(counts):
    """Maps speech counts to marker sizes using sqrt scaling (so area, not radius,
    is proportional to count — avoids overstating differences)."""
    counts = np.array(counts, dtype=float)
    if np.nanmax(counts) == 0:
        return np.full(len(counts), MARKER_MIN_SIZE)
    sqrt_counts = np.sqrt(counts)
    sqrt_max = np.nanmax(sqrt_counts)
    if sqrt_max == 0:
        return np.full(len(counts), MARKER_MIN_SIZE)
    return MARKER_MIN_SIZE + (sqrt_counts / sqrt_max) * (MARKER_MAX_SIZE - MARKER_MIN_SIZE)

SPEECH_COUNTS = {pol: len(df) for pol, df in politicians_dfs.items()}
MIN_SPEECHES_THRESHOLD = 100

def plot_mtld_trend(selected_pols, show_medians, show_overall_median):
    if not selected_pols:
        print("Select at least one politician.")
        return
    fig = go.Figure()
    x_line = np.array([0, 100])

    for pol in selected_pols:
        df = politicians_dfs[pol]
        name = display_name(pol)
        color = POL_INFO[pol]["color"]

        dates_parsed = pandas.to_datetime(df[DATE_COL], errors="coerce")
        valid = df["mtld"].notna() & dates_parsed.notna()
        vals = df.loc[valid, "mtld"].to_numpy()
        pct = compute_career_pct(df.loc[valid])

        med = np.median(vals) if len(vals) else np.nan

        if len(vals) < 2:
            print(f"Skipping trend for {name}: not enough data.")
            continue

        slope, intercept = np.polyfit(pct, vals, 1)
        y_line = slope * x_line + intercept

        direction = "↑" if slope > 0 else ("↓" if slope < 0 else "→")
        fig.add_scatter(
            x=x_line,
            y=y_line,
            mode="lines",
            name=f"{name} (Δ={slope:+.3f}/% {direction})",
            line=dict(color=color, width=3),
            legendgroup=pol,
        )
        if show_medians:
            fig.add_hline(y=med, line_dash="dash", line_color=color)
            fig.add_scatter(
                x=[None], y=[None],
                mode="lines",
                line=dict(color=color, dash="dash"),
                name=f"Median ({med:.2f})",
                legendgroup=pol,
                showlegend=True,
            )

    if show_overall_median:
        overall_med = GLOBAL_MTLD_MEDIAN
        fig.add_hline(y=overall_med, line_dash="dot", line_color="black", line_width=2)
        fig.add_scatter(
            x=[None], y=[None],
            mode="lines",
            line=dict(color="black", dash="dot", width=2),
            name=f"Median all speeches ({overall_med:.2f})",
            showlegend=True,
        )

    fig.update_layout(
        xaxis_title="Career progress (%)",
        yaxis_title="MTLD",
        template="plotly_white",
        autosize=True,
        height=PLOT_HEIGHT,
        margin=dict(t=20),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    )
    fig.update_xaxes(ticksuffix="%", range=[-2, 102])
    fig.show(config=DOWNLOAD_CONFIG)


def compute_career_pct(df, date_col=DATE_COL):
    """Maps each speech's date to 0-100% of that politician's own career span.
    Rows with unparseable dates are excluded (return NaN, filtered out by caller)."""
    dates = pandas.to_datetime(df[date_col], errors="coerce")
    valid_dates = dates.notna()
    dmin, dmax = dates[valid_dates].min(), dates[valid_dates].max()
    span_days = (dmax - dmin).days
    pct = np.full(len(df), np.nan)
    if span_days > 0:
        pct[valid_dates.to_numpy()] = (
            (dates[valid_dates] - dmin).dt.days / span_days * 100
        ).to_numpy()
    return pct

def plot_mtld_line(selected_pols, show_medians, show_overall_median, scale_dots):
    if not selected_pols:
        print("Select at least one politician.")
        return
    fig = go.Figure()
    steps = np.linspace(0, 100, CAREER_STEPS + 1)

    for pol in selected_pols:
        df = politicians_dfs[pol]
        name = display_name(pol)
        color = POL_INFO[pol]["color"]

        dates_parsed = pandas.to_datetime(df[DATE_COL], errors="coerce")
        valid = df["mtld"].notna() & dates_parsed.notna()
        vals = df.loc[valid, "mtld"].to_numpy()
        pct = compute_career_pct(df.loc[valid])

        med = np.median(vals) if len(vals) else np.nan

        y_curve = []
        n_curve = []
        for s in steps:
            window = np.abs(pct - s) <= CAREER_WINDOW_PCT
            n_in_window = window.sum()
            n_curve.append(n_in_window)
            y_curve.append(np.median(vals[window]) if n_in_window else np.nan)

        marker_sizes = scaled_marker_sizes(n_curve) if scale_dots else MARKER_MIN_SIZE + 3

        fig.add_scatter(
            x=steps,
            y=y_curve,
            mode="lines+markers",
            name=name,
            line=dict(color=color, width=2.5),
            marker=dict(color=color, size=marker_sizes),
            connectgaps=True,
            legendgroup=pol,
            customdata=n_curve,
            hovertemplate="Career: %{x:.0f}%<br>MTLD: %{y:.2f}<br>Speeches aggregated: %{customdata}<extra>%{fullData.name}</extra>",
        )
        if show_medians:
            fig.add_hline(y=med, line_dash="dash", line_color=color)
            fig.add_scatter(
                x=[None], y=[None],
                mode="lines",
                line=dict(color=color, dash="dash"),
                name=f"Median ({med:.2f})",
                legendgroup=pol,
                showlegend=True,
            )

    if show_overall_median:
        overall_med = GLOBAL_MTLD_MEDIAN
        fig.add_hline(y=overall_med, line_dash="dot", line_color="black", line_width=2)
        fig.add_scatter(
            x=[None], y=[None],
            mode="lines",
            line=dict(color="black", dash="dot", width=2),
            name=f"Median all speeches ({overall_med:.2f})",
            showlegend=True,
        )

    fig.update_layout(
        xaxis_title="Career progress (%)",
        yaxis_title="MTLD",
        template="plotly_white",
        autosize=True,
        height=PLOT_HEIGHT,
        margin=dict(t=20),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    )
    fig.update_xaxes(ticksuffix="%", range=[-2, 102])
    fig.show(config=DOWNLOAD_CONFIG)

# box plot helper
def darken_color(hex_color, factor=0.6):
    """Returns a darker version of hex_color. factor < 1 darkens, e.g. 0.6 = 60% brightness."""
    hex_color = hex_color.lstrip("#")
    r, g, b = (int(hex_color[i:i+2], 16) for i in (0, 2, 4))
    r, g, b = (int(c * factor) for c in (r, g, b))
    return f"#{r:02x}{g:02x}{b:02x}"

def plot_mtld_box(selected_pols, show_overall_median):
    if not selected_pols:
        print("Select at least one politician.")
        return
    fig = go.Figure()
    for pol in selected_pols:
        df = politicians_dfs[pol]
        vals = df["mtld"].dropna()
        color = POL_INFO[pol]["color"]
        fig.add_box(
            y=vals,
            name=f"{display_name(pol)}<br>(n={len(vals)})",
            line=dict(color=darken_color(color), width=1.5),
            fillcolor=color,
            opacity=0.85,
            legendgroup=pol,
            boxmean=True,
            showlegend=False,   # suppress legend entry for this box specifically
        )
    if show_overall_median:
        overall_med = GLOBAL_MTLD_MEDIAN
        fig.add_hline(y=overall_med, line_dash="dot", line_color="black", line_width=2)
        fig.add_scatter(
            x=[None], y=[None],
            mode="lines",
            line=dict(color="black", dash="dot", width=2),
            name=f"Median all speeches ({overall_med:.2f})",
            showlegend=True,
        )
    fig.update_layout(
        xaxis_title="Prime Ministers",
        yaxis_title="MTLD",
        template="plotly_white",
        autosize=True,
        height=PLOT_HEIGHT,
        margin=dict(t=20),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    )
    fig.show(config=DOWNLOAD_CONFIG)

def plot_mtld(selected_pols, view, show_medians, show_overall_median, scale_dots):
    if view == "Trend":
        plot_mtld_trend(selected_pols, show_medians, show_overall_median)    
    elif view == "Line":
        plot_mtld_line(selected_pols, show_medians, show_overall_median, scale_dots)
    else:
        plot_mtld_box(selected_pols, show_overall_median)


# --- checkbox grid (3 columns) ---
pol_names = list(politicians_dfs.keys())
checkboxes = []
for pol in pol_names:
    cb = widgets.Checkbox(
        value=(pol in ["meloni", "degasperi"]),
        description=display_name(pol),
        indent=False,
        layout=widgets.Layout(width="180px"),
    )
    cb.pol_key = pol
    checkboxes.append(cb)

# --- "All" checkbox ---
all_checkbox = widgets.Checkbox(
    value=False,
    description="All",
    indent=False,
    layout=widgets.Layout(width="180px"),
)

_syncing = False  # guard flag to prevent observer feedback loops

def apply_min100_filter(change=None):
    global _syncing
    _syncing = True
    active = min100_toggle.value
    for cb in checkboxes:
        eligible = SPEECH_COUNTS[cb.pol_key] > MIN_SPEECHES_THRESHOLD
        if active and not eligible:
            cb.value = False
            cb.disabled = True
        else:
            cb.disabled = False
    # keep "All" checkbox consistent with what's actually selectable
    selectable = [cb for cb in checkboxes if not cb.disabled]
    all_checkbox.value = bool(selectable) and all(cb.value for cb in selectable)
    _syncing = False
    redraw()

def on_all_change(change):
    global _syncing
    if _syncing:
        return
    _syncing = True
    for cb in checkboxes:
        if not cb.disabled:
            cb.value = change["new"]
    _syncing = False
    redraw()

def on_individual_change(change):
    global _syncing
    if _syncing:
        return
    _syncing = True
    selectable = [cb for cb in checkboxes if not cb.disabled]
    all_checkbox.value = bool(selectable) and all(cb.value for cb in selectable)
    _syncing = False
    redraw()

all_checkbox.observe(on_all_change, names="value")
for cb in checkboxes:
    cb.observe(on_individual_change, names="value")

checkbox_grid = widgets.GridBox(
    [all_checkbox] + checkboxes,
    layout=widgets.Layout(
        width="100%",
        grid_template_columns="repeat(auto-fill, minmax(150px, 1fr))",
    )
)

view_toggle = widgets.ToggleButtons(
    options=["Trend", "Line", "BoxPlot"],
    value="BoxPlot",
    description="View:",
)

median_toggle = widgets.Checkbox(
    value=True,
    description="Show medians",
    indent=False,
)

overall_median_toggle = widgets.Checkbox(
    value=False,
    description="Show median all speeches",
    indent=False,
)

size_toggle = widgets.Checkbox(
    value=False,
    description="Scale dots by speech count",
    indent=False,
)

min100_toggle = widgets.Checkbox(
    value=True,
    description="Only PMs with >100 speeches",
    indent=False,
)

for w in [median_toggle, overall_median_toggle, size_toggle, min100_toggle]:
    w.layout = widgets.Layout(width="auto", min_width="240px", margin="2px 10px 2px 0")

toggles_box = widgets.HBox(
    [median_toggle, overall_median_toggle, size_toggle, min100_toggle],
    layout=widgets.Layout(flex_flow="row wrap", width="100%"),
)

title_label = widgets.HTML()

def _title_html(view):
    return (
        f"<h2 style='margin: 12px 0 4px 0; font-family: sans-serif; text-align: center;'>"
        f"Lexical Diversity (MTLD) Comparison — {view}</h2>"
    )

title_label.value = _title_html(view_toggle.value)

output = widgets.Output()

def redraw(change=None):
    selected = [cb.pol_key for cb in checkboxes if cb.value]
    title_label.value = _title_html(view_toggle.value)
    median_toggle.disabled = (view_toggle.value == "BoxPlot")
    size_toggle.disabled = (view_toggle.value == "BoxPlot" or view_toggle.value == "Trend")
    with output:
        output.clear_output(wait=True)
        plot_mtld(
            selected, view_toggle.value,
            median_toggle.value, overall_median_toggle.value, size_toggle.value,
        )

size_toggle.observe(redraw, names="value")
view_toggle.observe(redraw, names="value")
median_toggle.observe(redraw, names="value")
overall_median_toggle.observe(redraw, names="value")  
min100_toggle.observe(apply_min100_filter, names="value")

apply_min100_filter()

display(checkbox_grid, view_toggle, toggles_box, title_label, output)
redraw()

GridBox(children=(Checkbox(value=False, description='All', indent=False, layout=Layout(width='180px')), Checkb…

ToggleButtons(description='View:', index=2, options=('Trend', 'Line', 'BoxPlot'), value='BoxPlot')

HTML(value="<h2 style='margin: 12px 0 4px 0; font-family: sans-serif; text-align: center;'>Lexical Diversity (…

Output()

#### Export In GitHub Pages


In [11]:
"""
Run this once inside your notebook (where `politicians_dfs` and `POL_COLORS`
already exist) to produce data.json for the GitHub Pages site.

Usage (in a notebook cell):
    exec(open("export_data.py").read())

Or just paste the body below directly into a cell.
"""

import json
from pathlib import Path


OUT_DIR = os.path.join(BASE_DIR, "docs")
os.makedirs(OUT_DIR, exist_ok=True)
OUT_PATH = Path(f"{OUT_DIR}/data.json")

data = {}
for pol, df in politicians_dfs.items():
    vals = df["mtld"].dropna().tolist()
    data[pol] = {
        "mtld": vals,
        "color": POL_INFO[pol]["color"],
    }

with OUT_PATH.open("w", encoding="utf-8") as f:
    json.dump(data, f)

print(f"Wrote {OUT_PATH.resolve()} with {len(data)} politicians")


Wrote /home/mhetac/Documents/GitHub/crossdem/docs/data.json with 25 politicians


### VDEM MTLD

In [12]:
vdem = pandas.read_csv(f"{DATA_DIR}/vdem/V-Dem-CY-Core-v16_csv/V-Dem-CY-Core-v16.csv") # not full df so ofcs no italy
italy = vdem[vdem["country_name"] == "Italy"]                               
#italy.head()
print(f"{italy["v2x_polyarchy"]}")

12702      NaN
12703    0.207
12704    0.207
12705    0.207
12706    0.205
         ...  
12862    0.857
12863    0.842
12864    0.806
12865    0.784
12866    0.745
Name: v2x_polyarchy, Length: 165, dtype: float64


#### VDem Needed Data
**CY Country Year:**
- year granularity
- 5 indices
- 93 sub-indices
- 179 indicators

Features:
- **Identifiers:**
  - `historical_date`
    - YYYY-MM-DD
    - $\in$ CY datasets but has no meaning
    - for election-date-specific variables
      - $\forall$ other variables $=1_st$ january
- **Democracy Indices:**
  - $1_st$ level indices
  - $\forall scale=[1,0]$ unless otherwise specified
  - `v2x_polyarchy`
    - *electoral* democracy index
  - `v2x_libdem`
    - *liberal* democracy index
  - `v2x_partipdem`
    - *participatory* democracy index
- **Components of Democracy Indices** 
  - $2_nd$ level indices
  - subcomponents of Democracy Indices
  - `v2xel_frefair`
    - elections quality
      - free
      - fair
  - `v2xcl_rol`
    - laws transparency
    - laws fair enforcement
    - individual rights and liberties
  - `v2xlg_legcon`
    - executive external scrutiny


In [13]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import ipywidgets as widgets
from IPython.display import display
from scipy.interpolate import UnivariateSpline

YEAR_MIN, YEAR_MAX = 1945, 2025

GROUPS = {
    "Combined":            None,
    "Left (CL/L)":    ("CL", "L"),
    "Right (CR/R)":   ("CR", "R"),
    "Center (C)":     ("C",),
}

GROUP_COLORS = {
    "Combined":          "#7f7f7f",
    "Left (CL/L)":  "#d62728",
    "Right (CR/R)": "#1f77b4",
    "Center (C)":   "#2ca02c",
}

# --- V-Dem: Italy, indices for overlay ---
VDEM_VARS = {
    "Electoral democracy": "v2x_polyarchy",
    "Liberal democracy":               "v2x_libdem",
    "Participatory democracy":         "v2x_partipdem",
    "Elections quality":  "v2xel_frefair",
    "Fairness of law and individual liberties":   "v2xcl_rol",
    "Scrutiny of executives": "v2xlg_legcon",
}

VDEM_COLORS = {
    "Electoral democracy": "#9467bd",
    "Liberal democracy":               "#8c564b",
    "Participatory democracy":         "#e377c2",
    "Elections quality":  "#17becf",
    "Fairness of law and individual liberties":   "#bcbd22",
    "Scrutiny of executives": "#ff7f0e",
}

italy_vdem = vdem[vdem["country_name"] == "Italy"][["year"] + list(VDEM_VARS.values())].copy()
italy_vdem = italy_vdem.set_index("year").sort_index()

MARKER_MIN_SIZE = 2
MARKER_MAX_SIZE = 16

BAR_MIN_WIDTH = 0.3
BAR_MAX_WIDTH = 0.9

BAR_MIN_CLUSTER = 0.8  
BAR_GAP = 0.3 

N_BOOTSTRAP = 1000
CI_LEVEL = 0.95

PERIOD_MAP = {"5 Years": 5, "10 Years": 10}

DOWNLOAD_CONFIG = {
    "toImageButtonOptions": {
        "format": "png", 
        "filename": "mtld_vdem", 
        "scale": 3
        }
    }

# --- box plot helper ---
def darken_color(hex_color, factor=0.6):
    """Returns a darker version of hex_color. factor < 1 darkens, e.g. 0.6 = 60% brightness."""
    hex_color = hex_color.lstrip("#")
    r, g, b = (int(hex_color[i:i+2], 16) for i in (0, 2, 4))
    r, g, b = (int(c * factor) for c in (r, g, b))
    return f"#{r:02x}{g:02x}{b:02x}"

# --- build one long dataframe: pol, year, mtld, leaning ---
def build_year_df():
    frames = []
    for pol, df in politicians_dfs.items():
        d = df[["historical_date", "mtld"]].dropna().copy()
        d["year"] = pd.to_datetime(d["historical_date"], errors="coerce").dt.year
        d["pol"] = pol
        d["leaning"] = POL_INFO[pol]["leaning"]
        frames.append(d)
    out = pd.concat(frames, ignore_index=True)
    out = out.dropna(subset=["year"])
    out["year"] = out["year"].astype(int)
    return out

all_speeches_df = build_year_df()

def print_speech_counts():
    total = len(all_speeches_df)
    print(f"Total speeches: {total}")
    for label, leanings in GROUPS.items():
        if leanings is None:
            continue  # skip "Combined", it's the same as total
        n = all_speeches_df[all_speeches_df["leaning"].isin(leanings)].shape[0]
        print(f"{label}: {n}")

print_speech_counts()

def scaled_marker_sizes(counts):
    """Maps speech counts to marker sizes using sqrt scaling (so area, not radius,
    is proportional to count — avoids overstating differences)."""
    counts = np.array(counts, dtype=float)
    if np.nanmax(counts) == 0:
        return np.full(len(counts), MARKER_MIN_SIZE)
    sqrt_counts = np.sqrt(counts)
    sqrt_max = np.nanmax(sqrt_counts)
    if sqrt_max == 0:
        return np.full(len(counts), MARKER_MIN_SIZE)
    return MARKER_MIN_SIZE + (sqrt_counts / sqrt_max) * (MARKER_MAX_SIZE - MARKER_MIN_SIZE)

def scaled_bar_widths(counts):
    """Maps speech counts to bar widths (in year units) using sqrt scaling,
    consistent with scaled_marker_sizes."""
    counts = np.array(counts, dtype=float)
    if np.nanmax(counts) == 0:
        return np.full(len(counts), BAR_MIN_WIDTH)
    sqrt_counts = np.sqrt(counts)
    sqrt_max = np.nanmax(sqrt_counts)
    if sqrt_max == 0:
        return np.full(len(counts), BAR_MIN_WIDTH)
    return BAR_MIN_WIDTH + (sqrt_counts / sqrt_max) * (BAR_MAX_WIDTH - BAR_MIN_WIDTH)

def compute_bar_layout(selected_groups, scale_dots):
    years = np.arange(YEAR_MIN, YEAR_MAX + 1)
    n = len(years)
    n_groups = len(selected_groups)

    widths_by_group = {}
    if scale_dots:
        for g in selected_groups:
            counts = yearly_counts(GROUPS[g]).reindex(years, fill_value=0).values
            widths_by_group[g] = scaled_bar_widths(counts)
    else:
        for g in selected_groups:
            widths_by_group[g] = np.full(n, BAR_MIN_CLUSTER / max(n_groups, 1))

    cluster_width = np.zeros(n)
    for g in selected_groups:
        cluster_width += widths_by_group[g]
    cluster_width = np.maximum(cluster_width, BAR_MIN_CLUSTER)

    slot_width = cluster_width + BAR_GAP
    left_edge = np.concatenate([[0.0], np.cumsum(slot_width)[:-1]])
    cluster_left = left_edge + BAR_GAP / 2
    year_pos = cluster_left + cluster_width / 2   # this year's position on the new axis

    x_by_group = {g: np.zeros(n) for g in selected_groups}
    running_left = cluster_left.copy()
    for g in selected_groups:
        w = widths_by_group[g]
        x_by_group[g] = running_left + w / 2
        running_left = running_left + w

    return years, year_pos, x_by_group, widths_by_group

def get_vdem_series(col):
    full_years = pd.RangeIndex(YEAR_MIN, YEAR_MAX + 1)
    return italy_vdem[col].reindex(full_years)

def yearly_counts(leanings):
    """Number of speeches aggregated into each year, for the given leaning filter."""
    d = all_speeches_df
    if leanings is not None:
        d = d[d["leaning"].isin(leanings)]
    s = d.groupby("year").size()
    full_years = pd.RangeIndex(YEAR_MIN, YEAR_MAX + 1)
    return s.reindex(full_years, fill_value=0)

#----- agnostic on speeches amount, aggregates to one value per year -----
def yearly_series(leanings, stat):
    d = all_speeches_df
    if leanings is not None:
        d = d[d["leaning"].isin(leanings)]
    agg_func = "median" if stat == "Median" else "mean"

    # step 1: collapse to one value per politician per year (removes speech-count weighting)
    pol_year = d.groupby(["year", "pol"])["mtld"].agg(agg_func)
    # step 2: aggregate across politicians, each counted once regardless of speech volume
    s = pol_year.groupby("year").agg(agg_func)

    full_years = pd.RangeIndex(YEAR_MIN, YEAR_MAX + 1)
    return s.reindex(full_years)

def yearly_ci(leanings, stat, n_boot=N_BOOTSTRAP, ci=CI_LEVEL, seed=42):
    """Bootstrap CI for the yearly aggregated stat, resampling at the
    politician level (matching the two-step aggregation in yearly_series)."""
    d = all_speeches_df
    if leanings is not None:
        d = d[d["leaning"].isin(leanings)]
    agg_func = "median" if stat == "Median" else "mean"

    # same first step as yearly_series: one value per politician per year
    pol_year = d.groupby(["year", "pol"])["mtld"].agg(agg_func)

    rng = np.random.default_rng(seed)
    alpha = (1 - ci) / 2
    full_years = pd.RangeIndex(YEAR_MIN, YEAR_MAX + 1)

    lower = pd.Series(index=full_years, dtype=float)
    upper = pd.Series(index=full_years, dtype=float)

    for year in full_years:
        if year not in pol_year.index.get_level_values("year"):
            continue
        vals = pol_year.loc[year].values
        if len(vals) < 2:
            continue  # can't bootstrap a meaningful CI from a single politician
        boot_stats = np.array([
            (np.median if stat == "Median" else np.mean)(rng.choice(vals, size=len(vals), replace=True))
            for _ in range(n_boot)
        ])
        lower[year] = np.quantile(boot_stats, alpha)
        upper[year] = np.quantile(boot_stats, 1 - alpha)

    return lower, upper

def compute_series(leanings, stat, mode, smooth_window, trend_s):
    s = yearly_series(leanings, stat)

    if mode == "Smoothed" and smooth_window > 1:
        s = s.rolling(window=smooth_window, center=True, min_periods=1, win_type="gaussian").mean(std=smooth_window / 3)

    elif mode == "Trend":
        valid = s.dropna()
        x = valid.index.values.astype(float)
        y = valid.values.astype(float)
        if len(x) < 4:
            # not enough points for a cubic spline; fall back to whatever order is possible
            k = max(1, len(x) - 1)
        else:
            k = 3
        if len(x) >= 2:
            spline = UnivariateSpline(x, y, k=k, s=trend_s, ext=3)
            full_x = s.index.values.astype(float)
            s = pd.Series(spline(full_x), index=s.index)
        # else: leave as-is (all-NaN), nothing to fit

    return s

def compute_series_with_ci(leanings, stat, mode, smooth_window, trend_s):
    s = compute_series(leanings, stat, mode, smooth_window, trend_s)
    lower, upper = yearly_ci(leanings, stat)

    if mode == "Smoothed" and smooth_window > 1:
        lower = lower.rolling(window=smooth_window, center=True, min_periods=1, win_type="gaussian").mean(std=smooth_window / 3)
        upper = upper.rolling(window=smooth_window, center=True, min_periods=1, win_type="gaussian").mean(std=smooth_window / 3)
    elif mode == "Trend":
        for bound_name, bound in [("lower", lower), ("upper", upper)]:
            valid = bound.dropna()
            if len(valid) >= 2:
                x = valid.index.values.astype(float)
                y = valid.values.astype(float)
                k = 3 if len(x) >= 4 else max(1, len(x) - 1)
                spline = UnivariateSpline(x, y, k=k, s=trend_s, ext=3)
                full_x = bound.index.values.astype(float)
                filled = pd.Series(spline(full_x), index=bound.index)
                if bound_name == "lower":
                    lower = filled
                else:
                    upper = filled

    return s, lower, upper


# ---------------- box plot period helpers ----------------

def get_periods(period_years):
    """Period start years, anchored at YEAR_MIN. If the trailing period would
    be shorter than a full period (e.g. just 2025-2025), it's merged into the
    previous bucket instead of standing alone as a near-empty stub."""
    starts = list(range(YEAR_MIN, YEAR_MAX + 1, period_years))
    if len(starts) > 1 and (YEAR_MAX - starts[-1] + 1) < period_years:
        starts = starts[:-1]
    return starts

def period_start_for_year(year, period_years):
    starts = get_periods(period_years)
    starts_arr = np.array(starts)
    idx = np.searchsorted(starts_arr, year, side="right") - 1
    idx = max(idx, 0)
    return starts[idx]

def period_label(start, period_years):
    starts = get_periods(period_years)
    idx = starts.index(start)
    end = (starts[idx + 1] - 1) if idx + 1 < len(starts) else YEAR_MAX
    return f"{start}-{end}"

def period_speech_counts(period_years):
    """Total speech count per period, regardless of political leaning —
    used purely to annotate the X axis with sample size."""
    d = all_speeches_df
    d = d[(d["year"] >= YEAR_MIN) & (d["year"] <= YEAR_MAX)].copy()
    d["period_start"] = d["year"].apply(lambda y: period_start_for_year(y, period_years))
    return d.groupby("period_start").size()

def build_box_data(leanings, stat, period_years):
    """Raw per-speech MTLD values within each period/group — unlike yearly_series,
    box plots should show actual distribution, so we do NOT collapse to one
    value per politician first (that would degenerate to a single point in
    periods dominated by one PM, e.g. De Gasperi 1945-1954)."""
    d = all_speeches_df
    d = d[(d["year"] >= YEAR_MIN) & (d["year"] <= YEAR_MAX)].copy()
    if leanings is not None:
        d = d[d["leaning"].isin(leanings)]
    d["period_start"] = d["year"].apply(lambda y: period_start_for_year(y, period_years))
    return d[["period_start", "mtld"]]


def plot_year_trends(selected_groups, stat, mode, smooth_window, trend_s, chart_type, selected_vdem, scale_dots, show_ci, period_years):
    if not selected_groups and not selected_vdem:
        print("Select at least one group or V-Dem index.")
        return
    fig = go.Figure()

    is_bar = (chart_type == "Bar")
    is_box = (chart_type == "Box")

    if is_bar:
        years, year_pos, x_by_group, widths_by_group = compute_bar_layout(selected_groups, scale_dots)
        year_to_pos = dict(zip(years, year_pos))
    elif is_box:
        starts = get_periods(period_years)
        n_periods = len(starts)
        counts_by_period = period_speech_counts(period_years)
        labels = [f"{period_label(s, period_years)}<br>n={int(counts_by_period.get(s, 0))}" for s in starts]
        label_map = dict(zip(starts, labels))

    for g in selected_groups:
        if is_box:
            pol_period = build_box_data(GROUPS[g], stat, period_years)
            fig.add_box(
                x=[label_map[s] for s in pol_period["period_start"]],
                y=pol_period["mtld"],
                name=g,
                fillcolor=GROUP_COLORS[g],
                line=dict(color=darken_color(GROUP_COLORS[g])),
                marker=dict(color=darken_color(GROUP_COLORS[g]), size=4),
                boxpoints="outliers",
                legendgroup=g,
            )
            continue

        s = compute_series(GROUPS[g], stat, mode, smooth_window, trend_s)

        # --- confidence interval band (Line chart types only) ---
        if show_ci and not is_bar and mode == "Trend":
            _, lower, upper = compute_series_with_ci(GROUPS[g], stat, mode, smooth_window, trend_s)
            fig.add_scatter(
                x=upper.index, y=upper.values,
                mode="lines",
                line=dict(width=0),
                showlegend=False,
                hoverinfo="skip",
                legendgroup=g,
            )
            fig.add_scatter(
                x=lower.index, y=lower.values,
                mode="lines",
                line=dict(width=0),
                fill="tonexty",
                fillcolor=_hex_to_rgba(GROUP_COLORS[g], 0.15),
                showlegend=False,
                hoverinfo="skip",
                legendgroup=g,
            )

        if is_bar:
            fig.add_bar(
                x=x_by_group[g],
                y=s.reindex(years).values,
                width=widths_by_group[g],
                name=g,
                marker=dict(color=GROUP_COLORS[g]),
            )
        else:
            line_kwargs = dict(color=GROUP_COLORS[g], width=2.5)
            if mode in ("Smoothed", "Trend"):
                line_kwargs["shape"] = "spline" if mode == "Smoothed" else "linear"
                plot_mode = "lines"
                marker_kwargs = dict(color=GROUP_COLORS[g], size=5)  # markers unused in these modes
            else:
                plot_mode = "lines+markers"
                if scale_dots:
                    counts = yearly_counts(GROUPS[g]).reindex(s.index, fill_value=0)
                    marker_kwargs = dict(color=GROUP_COLORS[g], size=scaled_marker_sizes(counts))
                else:
                    marker_kwargs = dict(color=GROUP_COLORS[g], size=5)
            fig.add_scatter(
                x=s.index,
                y=s.values,
                mode=plot_mode,
                name=g,
                line=line_kwargs,
                marker=marker_kwargs,
                connectgaps=True,
                legendgroup=g,
                customdata=(yearly_counts(GROUPS[g]).reindex(s.index, fill_value=0) if (mode == "Exact") else None),
                hovertemplate=(
                    "Year: %{x}<br>MTLD: %{y:.2f}<br>Speeches: %{customdata}<extra>%{fullData.name}</extra>"
                    if mode == "Exact" else
                    "Year: %{x}<br>MTLD: %{y:.2f}<extra>%{fullData.name}</extra>"
                ),
            )

    # V-Dem overlays: always a line, always on secondary axis. Skipped for Box
    # (period-binned distributions don't map cleanly onto a categorical axis).
    for v in selected_vdem:
        col = VDEM_VARS[v]
        s = get_vdem_series(col)
        if is_box:
            fig.add_scatter(
                x=s.index, y=s.values,
                mode="lines",
                name=v,
                line=dict(color=VDEM_COLORS[v], width=2, dash="dot"),
                xaxis="x2",
                yaxis="y2",
                connectgaps=True,
            )
        else:
            x_vals = [year_to_pos[y] for y in s.index] if is_bar else s.index
            fig.add_scatter(
                x=x_vals,
                y=s.values,
                mode="lines",
                name=v,
                line=dict(color=VDEM_COLORS[v], width=2, dash="dot"),
                yaxis="y2",
                connectgaps=True,
            )
    if is_bar:
        xaxis_kwargs = dict(
            tickmode="array",
            tickvals=year_pos[::5],
            ticktext=[str(y) for y in years[::5]],
            range=[year_pos[0] - BAR_GAP, year_pos[-1] + BAR_GAP],
        )
    elif is_box:
        xaxis_kwargs = dict(
            categoryorder="array",
            categoryarray=labels,
            range=[-0.5, n_periods - 0.5],
        )
    else:
        xaxis_kwargs = dict(range=[YEAR_MIN, YEAR_MAX], dtick=5)

    layout_kwargs = dict(
        xaxis_title=("Period (speech count)" if is_box else "Year"),
        yaxis_title=f"{stat} MTLD",
        xaxis=xaxis_kwargs,
        yaxis2=dict(title="V-Dem index (0–1)", overlaying="y", side="right", range=[0, 1], showgrid=False),
        template="plotly_white",
        autosize=True,
        height=600,
        margin=dict(t=60),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        barmode="overlay",
        boxmode="group",
    )
    if is_box:
        layout_kwargs["xaxis2"] = dict(
            overlaying="x",
            side="top",
            range=[YEAR_MIN, YEAR_MIN + n_periods * period_years],
            showgrid=False,
            title="Year (V-Dem)",
        )
    fig.update_layout(**layout_kwargs)
    fig.show(config=DOWNLOAD_CONFIG)


def _hex_to_rgba(hex_color, alpha):
    hex_color = hex_color.lstrip("#")
    r, g, b = (int(hex_color[i:i+2], 16) for i in (0, 2, 4))
    return f"rgba({r},{g},{b},{alpha})"

# --- widgets ---

group_checkboxes = []
for g in GROUPS:
    cb = widgets.Checkbox(value=(g == "Combined"), description=g, indent=False,
                           layout=widgets.Layout(width="180px"))
    cb.group_key = g
    group_checkboxes.append(cb)

group_grid = widgets.GridBox(
    group_checkboxes,
    layout=widgets.Layout(width="100%", grid_template_columns="repeat(auto-fill, minmax(160px, 1fr))"),
)

vdem_checkboxes = []
for v in VDEM_VARS:
    cb = widgets.Checkbox(value=False, description=v, indent=False,
                           layout=widgets.Layout(width="260px"))
    cb.var_key = v
    vdem_checkboxes.append(cb)

vdem_grid = widgets.GridBox(
    vdem_checkboxes,
    layout=widgets.Layout(width="100%", grid_template_columns="repeat(auto-fill, minmax(240px, 1fr))"),
)

stat_toggle = widgets.ToggleButtons(
    options=["Median", "Average"],
    value="Median",
    description="Stat:",
)

mode_toggle = widgets.ToggleButtons(
    options=["Exact", "Smoothed", "Trend"],
    value="Exact",
    description="Mode:",
)

chart_type_toggle = widgets.ToggleButtons(
    options=["Line", "Bar", "Box"],
    value="Line",
    description="Chart:",
)

period_toggle = widgets.ToggleButtons(
    options=["5 Years", "10 Years"],
    value="5 Years",
    description="Period:",
    disabled=True,
)

size_toggle = widgets.Checkbox(
    value=False,
    description="Scale by speech count",
    indent=False,
)

smooth_slider = widgets.IntSlider(
    value=5, min=1, max=15, step=1,
    description="Smoothing:",
    continuous_update=False,
    disabled=True,
)

trend_slider = widgets.FloatSlider(
    value=8, min=0, max=50, step=0.5,
    description="Trend s:",
    continuous_update=False,
    disabled=True,
    tooltip="Spline smoothing factor: 0 = interpolate exactly through points, higher = smoother/flatter curve",
)

ci_toggle = widgets.Checkbox(value=False, description="Show confidence intervals", indent=False)

output = widgets.Output()

def on_chart_type_change(change):
    if change["new"] in ("Bar", "Box") and mode_toggle.value != "Exact":
        mode_toggle.value = "Exact"  # triggers redraw via mode_toggle's own observer
    else:
        redraw()

def redraw(change=None):
    selected = [cb.group_key for cb in group_checkboxes if cb.value]
    selected_vdem = [cb.var_key for cb in vdem_checkboxes if cb.value]

    chart_type = chart_type_toggle.value
    mode = mode_toggle.value
    is_box = (chart_type == "Box")

    mode_toggle.disabled = (chart_type in ("Bar", "Box"))
    smooth_slider.disabled = (mode != "Smoothed")
    trend_slider.disabled = (mode != "Trend")
    ci_toggle.disabled = not (chart_type == "Line" and mode == "Trend")
    size_toggle.disabled = not (chart_type == "Bar" or (chart_type == "Line" and mode == "Exact"))
    period_toggle.disabled = not is_box

    with output:
        output.clear_output(wait=True)
        plot_year_trends(
            selected, stat_toggle.value, mode,
            smooth_slider.value, trend_slider.value,
            chart_type, selected_vdem,
            size_toggle.value, ci_toggle.value,
            PERIOD_MAP[period_toggle.value],
        )



for cb in group_checkboxes:
    cb.observe(redraw, names="value")
for cb in vdem_checkboxes:
    cb.observe(redraw, names="value")
stat_toggle.observe(redraw, names="value")
mode_toggle.observe(redraw, names="value")
chart_type_toggle.observe(on_chart_type_change, names="value")
period_toggle.observe(redraw, names="value")
smooth_slider.observe(redraw, names="value")
trend_slider.observe(redraw, names="value")
size_toggle.observe(redraw, names="value")
ci_toggle.observe(redraw, names="value")


display(group_grid, widgets.HTML("<b>V-Dem indices (Italy):</b>"), vdem_grid,
        stat_toggle, mode_toggle, chart_type_toggle, period_toggle, smooth_slider, trend_slider,
        size_toggle, ci_toggle, output)
redraw()

Total speeches: 5979
Left (CL/L): 3579
Right (CR/R): 1672
Center (C): 728


GridBox(children=(Checkbox(value=True, description='Combined', indent=False, layout=Layout(width='180px')), Ch…

HTML(value='<b>V-Dem indices (Italy):</b>')

GridBox(children=(Checkbox(value=False, description='Electoral democracy', indent=False, layout=Layout(width='…

ToggleButtons(description='Stat:', options=('Median', 'Average'), value='Median')

ToggleButtons(description='Mode:', options=('Exact', 'Smoothed', 'Trend'), value='Exact')

ToggleButtons(description='Chart:', options=('Line', 'Bar', 'Box'), value='Line')

ToggleButtons(description='Period:', disabled=True, options=('5 Years', '10 Years'), value='5 Years')

IntSlider(value=5, continuous_update=False, description='Smoothing:', disabled=True, max=15, min=1)

FloatSlider(value=8.0, continuous_update=False, description='Trend s:', disabled=True, max=50.0, step=0.5, too…

Checkbox(value=False, description='Scale by speech count', indent=False)

Checkbox(value=False, description='Show confidence intervals', indent=False)

Output()

In [14]:
"""
export_data.py

Run this in the SAME kernel/notebook as your existing MTLD dashboard code,
right after the cells that build `politicians_dfs`, `POL_LEANING` and load
`vdem`. It reuses your existing GROUPS / VDEM_VARS definitions and pre-computes
every value the static site could ever need (exact yearly series, every
Gaussian-smoothed window 1-15, and every spline-trend s value on a 0.5 grid),
so the HTML/JS side never has to reimplement pandas rolling() or
UnivariateSpline — it just looks values up.

Output: data.json next to index.html.
"""

import json
import numpy as np
import pandas as pd
from scipy.interpolate import UnivariateSpline

YEAR_MIN, YEAR_MAX = 1945, 2025
YEARS = list(range(YEAR_MIN, YEAR_MAX + 1))

GROUPS = {
    "Combined": None,
    "Left (CL/L)": ("CL", "L"),
    "Right (CR/R)": ("CR", "R"),
    "Center (C)": ("C",),
}

VDEM_VARS = {
    "Electoral democracy": "v2x_polyarchy",
    "Liberal democracy": "v2x_libdem",
    "Participatory democracy": "v2x_partipdem",
    "Elections quality": "v2xel_frefair",
    "Fairness of law and individual liberties": "v2xcl_rol",
    "Scrutiny of executives": "v2xlg_legcon",
}

STATS = ["Median", "Average"]
SMOOTH_WINDOWS = list(range(1, 16))          # matches smooth_slider 1..15 step 1
TREND_S_VALUES = [round(x * 0.5, 1) for x in range(0, 101)]  # 0..50 step 0.5


# ---------- rebuild the long dataframe (same logic as the notebook) ----------
def build_year_df():
    frames = []
    for pol, df in politicians_dfs.items():
        d = df[["historical_date", "mtld"]].dropna().copy()
        d["year"] = pd.to_datetime(d["historical_date"], errors="coerce").dt.year
        d["pol"] = pol
        d["leaning"] = POL_INFO[pol]["leaning"]
        frames.append(d)
    out = pd.concat(frames, ignore_index=True)
    out = out.dropna(subset=["year"])
    out["year"] = out["year"].astype(int)
    return out


all_speeches_df = build_year_df()


def yearly_series(leanings, stat):
    d = all_speeches_df
    if leanings is not None:
        d = d[d["leaning"].isin(leanings)]
    agg_func = "median" if stat == "Median" else "mean"

    pol_year = d.groupby(["year", "pol"])["mtld"].agg(agg_func)
    s = pol_year.groupby("year").agg(agg_func)

    full_years = pd.RangeIndex(YEAR_MIN, YEAR_MAX + 1)
    return s.reindex(full_years)


def smoothed(s, window):
    if window <= 1:
        return s
    return s.rolling(window=window, center=True, min_periods=1,
                      win_type="gaussian").mean(std=window / 3)


def trended(s, trend_s):
    valid = s.dropna()
    x = valid.index.values.astype(float)
    y = valid.values.astype(float)
    if len(x) < 2:
        return pd.Series(np.nan, index=s.index)
    k = 3 if len(x) >= 4 else max(1, len(x) - 1)
    spline = UnivariateSpline(x, y, k=k, s=trend_s, ext=3)
    full_x = s.index.values.astype(float)
    return pd.Series(spline(full_x), index=s.index)


def series_to_list(s):
    # NaN -> None so it round-trips through JSON as `null`
    return [None if pd.isna(v) else round(float(v), 4) for v in s.values]


# ---------------------------- assemble data.json ----------------------------
data = {
    "year_min": YEAR_MIN,
    "year_max": YEAR_MAX,
    "years": YEARS,
    "groups": list(GROUPS.keys()),
    "stats": STATS,
    "smooth_windows": SMOOTH_WINDOWS,
    "trend_s_values": TREND_S_VALUES,
    "vdem_vars": list(VDEM_VARS.keys()),
    "exact": {},
    "smoothed": {},
    "trend": {},
    "vdem": {},
}

for g, leanings in GROUPS.items():
    data["exact"][g] = {}
    data["smoothed"][g] = {}
    data["trend"][g] = {}
    for stat in STATS:
        base = yearly_series(leanings, stat)
        data["exact"][g][stat] = series_to_list(base)

        data["smoothed"][g][stat] = {
            str(w): series_to_list(smoothed(base, w)) for w in SMOOTH_WINDOWS
        }

        data["trend"][g][stat] = {
            str(s_val): series_to_list(trended(base, s_val)) for s_val in TREND_S_VALUES
        }
        print(f"done: {g} / {stat}")

italy_vdem = vdem[vdem["country_name"] == "Italy"][["year"] + list(VDEM_VARS.values())].copy()
italy_vdem = italy_vdem.set_index("year").sort_index()
full_years_idx = pd.RangeIndex(YEAR_MIN, YEAR_MAX + 1)

for label, col in VDEM_VARS.items():
    s = italy_vdem[col].reindex(full_years_idx)
    data["vdem"][label] = series_to_list(s)

with open(f"{BASE_DIR}/docs/mtld_vdem/data.json", "w") as f:
    json.dump(data, f)

print("Wrote data.json")

done: Combined / Median
done: Combined / Average
done: Left (CL/L) / Median
done: Left (CL/L) / Average
done: Right (CR/R) / Median


/tmp/ipykernel_70893/3573340443.py:89: UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  spline = UnivariateSpline(x, y, k=k, s=trend_s, ext=3)
/tmp/ipykernel_70893/3573340443.py:89: UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  spline = UnivariateSpline(x, y, k=k, s=trend_s, ext=3)


done: Right (CR/R) / Average
done: Center (C) / Median
done: Center (C) / Average
Wrote data.json



# Vocabulary Differences
> What are words that are used by De Gasperi and not by Meloni? And vice-versa

> What are the words most commonly used by De Gasperi and what by Meloni? 


In [15]:
# --- Tokenize and collect words (lowercase, alpha only) ---
def tokenize(text):
    return [token.text.lower() for token in nlp(text) 
            if token.is_alpha 
            and not token.is_stop 
            and len(token)>3
            ]

politician_words = {}
for pol, df in politicians_dfs.items():
    words = []
    for text in df["text"].dropna():
        words.extend(tokenize(text))
    politician_words[pol] = words



## Lexicon Matrices 

### Top 1000 in common

In [16]:
# -------------------------------------
# Top-1000 word sets per politician
# -------------------------------------
import pandas as pd
import numpy as np
from collections import Counter
import plotly.graph_objects as go
from scipy.cluster.hierarchy import linkage, leaves_list
from scipy.spatial.distance import squareform

politician_freq = {pol: Counter(words) for pol, words in politician_words.items()}
politician_top1000 = {
    pol: {word for word, _ in freq.most_common(1000)}
    for pol, freq in politician_freq.items()
}


### Jaccard Index and Top1000 Matrices

In [17]:
# -------------------------------------
# Overlap matrix (politicians x politicians)
# -------------------------------------
politicians = list(politicians_dfs.keys())

overlap_matrix = pd.DataFrame(index=politicians, columns=politicians, dtype=int)

for p1 in politicians:
    for p2 in politicians:
        set1 = politician_top1000[p1]
        set2 = politician_top1000[p2]
        overlap = set1 & set2
        union = set1 | set2
        overlap_matrix.loc[p1, p2] = len(overlap)

print("=== Top-1000 Overlap Matrix (words in common) ===")
print(overlap_matrix)

=== Top-1000 Overlap Matrix (words in common) ===
            degasperi  fanfani   leone   rumor  colombo  andreotti  cossiga  \
degasperi      1000.0    501.0   318.0   362.0    304.0      596.0    569.0   
fanfani         501.0   1000.0   287.0   372.0    285.0      533.0    478.0   
leone           318.0    287.0  1000.0   225.0    173.0      374.0    379.0   
rumor           362.0    372.0   225.0  1000.0    239.0      419.0    373.0   
colombo         304.0    285.0   173.0   239.0   1000.0      307.0    275.0   
andreotti       596.0    533.0   374.0   419.0    307.0     1000.0    683.0   
cossiga         569.0    478.0   379.0   373.0    275.0      683.0   1000.0   
forlani         550.0    546.0   314.0   434.0    304.0      643.0    564.0   
spadolini       609.0    542.0   347.0   420.0    312.0      671.0    637.0   
craxi           598.0    553.0   323.0   418.0    327.0      644.0    593.0   
goria           522.0    530.0   309.0   420.0    306.0      616.0    553.0   
de

In [18]:
# -------------------------------------
# Full-vocabulary word sets per politician
# -------------------------------------
politician_fullvocab = {
    pol: set(words) for pol, words in politician_words.items()
}

# -------------------------------------
# Overlap + Jaccard matrices (politicians x politicians) — full vocabulary
# -------------------------------------
politicians = list(politicians_dfs.keys())

jaccard_matrix_full = pd.DataFrame(index=politicians, columns=politicians, dtype=float)

for p1 in politicians:
    for p2 in politicians:
        set1 = politician_fullvocab[p1]
        set2 = politician_fullvocab[p2]
        overlap = set1 & set2
        union = set1 | set2
        jaccard_matrix_full.loc[p1, p2] = len(overlap) / len(union) if union else 0.0

print()
print("=== Full-Vocabulary Jaccard Similarity Matrix ===")
print(jaccard_matrix_full.round(3))

# -------------------------------------
# Optional: sanity check on vocabulary size imbalance
# -------------------------------------
vocab_sizes = {pol: len(s) for pol, s in politician_fullvocab.items()}
print("\n=== Unique word count per politician (full vocab) ===")
for pol, n in sorted(vocab_sizes.items(), key=lambda x: -x[1]):
    print(f"{pol:30s} {n}")


=== Full-Vocabulary Jaccard Similarity Matrix ===
            degasperi  fanfani  leone  rumor  colombo  andreotti  cossiga  \
degasperi       1.000    0.117  0.044  0.056    0.030      0.299    0.270   
fanfani         0.117    1.000  0.128  0.175    0.099      0.093    0.102   
leone           0.044    0.128  1.000  0.134    0.098      0.035    0.041   
rumor           0.056    0.175  0.134  1.000    0.127      0.045    0.052   
colombo         0.030    0.099  0.098  0.127    1.000      0.023    0.026   
andreotti       0.299    0.093  0.035  0.045    0.023      1.000    0.286   
cossiga         0.270    0.102  0.041  0.052    0.026      0.286    1.000   
forlani         0.233    0.211  0.087  0.121    0.061      0.203    0.212   
spadolini       0.274    0.156  0.062  0.082    0.041      0.253    0.252   
craxi           0.290    0.167  0.065  0.087    0.046      0.257    0.253   
goria           0.193    0.224  0.096  0.134    0.072      0.164    0.178   
de mita         0.282    

### Heatmap

In [19]:
import plotly.graph_objects as go
import ipywidgets as widgets
from IPython.display import display
from scipy.cluster.hierarchy import linkage, leaves_list, optimal_leaf_ordering
from scipy.spatial.distance import squareform
import numpy as np

# -------------------------------------
# Optimal leaf ordering (computed once, shared by both matrices)
# -------------------------------------
dist_matrix = 1 - jaccard_matrix_full.values.astype(float)
np.fill_diagonal(dist_matrix, 0)
condensed = squareform(dist_matrix, checks=False)

Z = linkage(condensed, method="average")
Z_ordered = optimal_leaf_ordering(Z, condensed)
order = leaves_list(Z_ordered)

ordered_politicians = [politicians[i] for i in order]
overlap_matrix_ordered = overlap_matrix.loc[ordered_politicians, ordered_politicians]
jaccard_matrix_ordered = jaccard_matrix_full.loc[ordered_politicians, ordered_politicians]

# -------------------------------------
# Config
# -------------------------------------
PALETTE = "YlGnBu"   # <-- change to any Plotly colorscale name, e.g. "Viridis", "Blues", "Reds", "Cividis"

MATRICES = {
    "Overlap":  dict(matrix=overlap_matrix_ordered, title="Top-1000 Overlap Matrix (words in common)", fmt="{:.0f}"),
    "Jaccard":  dict(matrix=jaccard_matrix_ordered, title="Jaccard Similarity Matrix",                 fmt="{:.2f}"),
}

DOWNLOAD_CONFIG = {
    "responsive": True,
    "toImageButtonOptions": {
        "format": "png",
        "filename": "similarity_heatmap",
        "scale": 3,
    },
}

PLOT_HEIGHT = 1200

# -------------------------------------
# Heatmap helper
# -------------------------------------
def plot_matrix_heatmap(matrix, title, colorscale, value_format="{:.0f}"):
    politicians_ax = list(matrix.index)

    fig = go.Figure(data=go.Heatmap(
        z=matrix.values.astype(float),
        x=politicians_ax,
        y=politicians_ax,
        colorscale=colorscale,
        text=matrix.map(lambda v: value_format.format(v)).values,
        texttemplate="%{text}",
        textfont={"size": 11},
        hovertemplate="%{y} vs %{x}<br>Value: %{z}<extra></extra>",
        colorbar=dict(title=""),
    ))

    fig.update_layout(
        title=title,
        xaxis=dict(side="bottom", tickangle=-45, constrain="domain"),
        yaxis=dict(autorange="reversed", scaleanchor="x", scaleratio=1, constrain="domain"),
        autosize=True,
        height=PLOT_HEIGHT,
        margin=dict(l=100, r=50, t=80, b=100),
    )
    fig.show(config=DOWNLOAD_CONFIG)

# -------------------------------------
# Widgets
# -------------------------------------
matrix_toggle = widgets.ToggleButtons(
    options=list(MATRICES.keys()),
    value="Overlap",
    description="Matrix:",
)

output = widgets.Output(layout=widgets.Layout(width="100%"))

def redraw(change=None):
    cfg = MATRICES[matrix_toggle.value]
    with output:
        output.clear_output(wait=True)
        plot_matrix_heatmap(cfg["matrix"], cfg["title"], PALETTE, cfg["fmt"])

matrix_toggle.observe(redraw, names="value")

display(
    matrix_toggle,
    output,
)
redraw()

ToggleButtons(description='Matrix:', options=('Overlap', 'Jaccard'), value='Overlap')

Output(layout=Layout(width='100%'))

In [20]:
"""
Run this AFTER the clustering/ordering cell in the notebook, i.e. once
overlap_matrix_ordered and jaccard_matrix_ordered already exist.

It just serializes the two ordered DataFrames (same politician order on
both axes, as produced by leaves_list(Z)) into a single data.json that
the static index.html page can fetch and render with Plotly.js.
"""

import json


def export_similarity_data(overlap_matrix_ordered, jaccard_matrix_ordered):
    politicians = list(overlap_matrix_ordered.index)

    output_path = f"{BASE_DIR}/docs/heatmap_pms"
    os.makedirs(output_path, exist_ok=True)

    # sanity check: both matrices must share the same ordered index
    assert politicians == list(jaccard_matrix_ordered.index), \
        "overlap_matrix_ordered and jaccard_matrix_ordered must share the same row order"

    data = {
        "politicians": politicians,
        "overlap_matrix": overlap_matrix_ordered.values.astype(float).tolist(),
        "jaccard_matrix": jaccard_matrix_ordered.values.round(4).astype(float).tolist(),
    }

    with open(f"{output_path}/data.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


    print(f"Exported {len(politicians)} politicians to {output_path}")


# --- run it ---
export_similarity_data(overlap_matrix_ordered, jaccard_matrix_ordered)

Exported 25 politicians to /home/mhetac/Documents/GitHub/crossdem/docs/heatmap_pms


## Polarization 

In [21]:
import re
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import ipywidgets as widgets
from IPython.display import display
from collections import Counter
import spacy

# -------------------------------------
# Config
# -------------------------------------
YEAR_MIN, YEAR_MAX = 1945, 2025
PERIOD_YEARS = 5
MIN_WORD_LEN = 3
TOP_N_OPTIONS = {"Top 1000": 1000, "Top 10000": 10000}

LEANING_GROUPS = {
    "L": ("CL", "L"),
    "R": ("CR", "R"),
    "C": ("C",),
}

BAR_COLORS = {
    "Common":  "#7f7f7f",
    "L_only":  "#d62728",
    "R_only":  "#1f77b4",
    "C_only":  "#2ca02c",
}

PLOT_HEIGHT = 600

# -------------------------------------
# Step 1: {historical_date, leaning_group, text}
# -------------------------------------
def classify(leaning):
    for key, leanings in LEANING_GROUPS.items():
        if leaning in leanings:
            return key
    return None

def build_leaning_speech_df():
    frames = []
    for pol, df in politicians_dfs.items():
        g = classify(POL_INFO[pol]["leaning"])
        if g is None:
            continue
        d = df[["historical_date", "text"]].dropna().copy()
        d["year"] = pd.to_datetime(d["historical_date"], errors="coerce").dt.year
        d["leaning_group"] = g
        frames.append(d[["year", "leaning_group", "text"]])
    out = pd.concat(frames, ignore_index=True)
    out = out.dropna(subset=["year"])
    out["year"] = out["year"].astype(int)
    return out

leaning_speech_df = build_leaning_speech_df()

# -------------------------------------
# Period helpers
# -------------------------------------
def get_periods(period_years):
    starts = list(range(YEAR_MIN, YEAR_MAX + 1, period_years))
    if len(starts) > 1 and (YEAR_MAX - starts[-1] + 1) < period_years:
        starts = starts[:-1]
    return starts

def period_end(start, period_years):
    starts = get_periods(period_years)
    idx = starts.index(start)
    return (starts[idx + 1] - 1) if idx + 1 < len(starts) else YEAR_MAX

def period_start_for_year(year, period_years):
    starts = np.array(get_periods(period_years))
    idx = np.searchsorted(starts, year, side="right") - 1
    idx = max(idx, 0)
    return starts[idx]

leaning_speech_df["period_start"] = leaning_speech_df["year"].apply(
    lambda y: period_start_for_year(y, PERIOD_YEARS)
)

# -------------------------------------
# Tokenization
# -------------------------------------

nlp = spacy.load("it_core_news_sm", disable=["parser", "ner"])
STOPWORDS = nlp.Defaults.stop_words

# Extra stopwords for transcription/subtitle artifacts (not real vocabulary)
CUSTOM_STOPWORDS_ARTIFACTS = {
    "qtss",
    "sottotitoli",
    "sottotitolo",
    "sottotitolato",
    "sottotitolazione",
    "amara",
    "org",
    "cioè",
    "insomma",
    "dico",
    "dicevo",
    "dicevamo",
    "dicevano",
    "allora",
    "dunque",
    "quindi",
    "praticamente",
    "sostanzialmente",
    "ovviamente",
    "evidentemente",
    "naturalmente",
    "certamente",
    "sicuramente",
    "chiaramente",
    "semplicemente",
    "francamente",
    "effettivamente",
    "esattamente",
    "davvero",
    "veramente",
    "sicuramente",
    "giustamente",
    "praticamente",
    "molto",
    "tanto",
    "poco",
    "abbastanza",
    "parecchio",
    "piuttosto",
    "decisamente",
    "particolarmente",
    "specialmente",
    "assai",
    "veramente",
    "persona",
    "uomo",
    "gente",
    "chiunque",
    "qualcuno",
    "qualcosa",
    "qualche",
    "ognuno",
    "ciascuno",
    "primo",
    "secondo",
    "terzo",
    "ultimo",
    "altro",
    "quarto",
    "quinto",
    "dodici ",
    "siccome",
    "that",
    "this",
    "these",
    "those",
    "the",
    "and",
    "which",
    "what",
    "who",
    "has",
    "have",
    "had",
    "been",
    "being",
    "from",
    "with",
    "into",
    "through",
    "about",
    "also",
    "their",
    "its",
    "our",
    "your",
    "one",
    "two",
    "three",
    "said",
    "were",
    "are",
    "was",
    "would",
    "could",
    "should",
    "will",
    "can",
    "may",
    "might",
    "must",
    "more",
    "most",
    "other",
    "each",
    "both",
    "some",
    "such",
    "any",
    "out",
    "than",
    "then",
    "when",
    "where",
    "while",
    "not",
    "for",
    "but",
    "so",
    "if",
    "no",
    "do",
    "did",
    "does",
    "went",
    "came",
    "comunque",
    "altrettanto",
    "piuttosto",
    "praticamente",
    "oltretutto",
    "perlomeno",
    "dunque",
    "poiché",
    "siccome",
    "affinché",
    "emmai",
    "sebbene",
}
STOPWORDS = STOPWORDS | CUSTOM_STOPWORDS_ARTIFACTS

TOKEN_RE = re.compile(r"^[a-zà-ú0-9]+$", re.IGNORECASE)

# Matches the amara.org subtitle credit line (adjust once you've confirmed
# the exact wording from a raw transcript sample)
BOILERPLATE_RE = re.compile(
    r"sottotitoli?\s+(creati|a\s+cura)\s+(dalla\s+comunit[aà]\s+)?amara\.?\s*org",
    re.IGNORECASE,
)

def strip_boilerplate(text):
    return BOILERPLATE_RE.sub(" ", text)

def tokenize(text):
    text = strip_boilerplate(text)
    doc = nlp(text.lower())
    return [
        tok.lemma_ for tok in doc
        if len(tok.lemma_) > MIN_WORD_LEN
        and TOKEN_RE.match(tok.lemma_)
        and tok.lemma_ not in STOPWORDS
        and not tok.lemma_.isdigit()
        and tok.is_alpha  # spaCy's own alpha check, extra safety net
    ]
# -------------------------------------
# Build FULL (uncapped) counters once per period+group — expensive step, done once
# -------------------------------------
def build_period_counters(period_years):
    starts = get_periods(period_years)
    counters = {}  # counters[start][group] -> Counter (full, uncapped)
    for s in starts:
        d = leaning_speech_df[leaning_speech_df["period_start"] == s]
        counters[s] = {}
        for g in ("L", "R", "C"):
            texts = d[d["leaning_group"] == g]["text"]
            c = Counter()
            for t in texts:
                c.update(tokenize(t))
            counters[s][g] = c
    return counters

print("Tokenizing and counting all periods/groups (this runs once)...")
PERIOD_COUNTERS = build_period_counters(PERIOD_YEARS)
print("Done.")

# -------------------------------------
# Cheap re-slice: top-N set + ranked list from a precomputed counter
# -------------------------------------
def top_n_from_counter(counter, n):
    ranked = [w for w, _ in counter.most_common(n)]
    return set(ranked), ranked

def period_top_sets(start, top_n):
    sets, ranked = {}, {}
    for g in ("L", "R", "C"):
        c = PERIOD_COUNTERS[start][g]
        if len(c) > 0:
            sets[g], ranked[g] = top_n_from_counter(c, top_n)
        else:
            sets[g], ranked[g] = set(), []
    return sets, ranked

def period_word_breakdown(start, top_n):
    sets, ranked = period_top_sets(start, top_n)
    L, R, C = sets["L"], sets["R"], sets["C"]

    present = [g for g in ("L", "R", "C") if len(sets[g]) > 0]
    common_all = set.intersection(*(sets[g] for g in present)) if len(present) >= 2 else set()

    l_only = L - R - C
    r_only = R - L - C
    c_only = C - L - R

    return {
        "Common": len(common_all),
        "L_only": len(l_only),
        "R_only": len(r_only),
        "C_only": len(c_only),
        "_sets": {"L_only": l_only, "R_only": r_only, "C_only": c_only, "Common": common_all},
        "_ranked": ranked,
    }

# -------------------------------------
# Print top words per bar for a given period
# -------------------------------------
def print_period_words(start, top_n, top_n_print=20):
    breakdown = period_word_breakdown(start, top_n)
    sets = breakdown["_sets"]
    ranked = breakdown["_ranked"]
    end = period_end(start, PERIOD_YEARS)

    print(f"---- {start}-{end} ----")

    def top_words_in_order(word_set, group_for_order):
        ordered = [w for w in ranked[group_for_order] if w in word_set]
        return ordered[:top_n_print]

    print("Right only:")
    print(" ".join(top_words_in_order(sets["R_only"], "R")) or "(none)")
    print()
    print("Left only:")
    print(" ".join(top_words_in_order(sets["L_only"], "L")) or "(none)")
    print()
    print("Center only:")
    print(" ".join(top_words_in_order(sets["C_only"], "C")) or "(none)")
    print()
    print("In Common:")
    order_group = next((g for g in ("L", "R", "C") if ranked[g]), "L")
    print(" ".join(top_words_in_order(sets["Common"], order_group)) or "(none)")
    print()

# -------------------------------------
# Widgets: TOP_N toggle
# -------------------------------------
topn_toggle = widgets.ToggleButtons(
    options=list(TOP_N_OPTIONS.keys()),
    value="Top 1000",
    description="Vocab size:",
)

output = widgets.Output(layout=widgets.Layout(width="100%"))

def redraw(change=None):
    top_n = TOP_N_OPTIONS[topn_toggle.value]
    starts = get_periods(PERIOD_YEARS)
    rows = [period_word_breakdown(s, top_n) for s in starts]
    period_df = pd.DataFrame(rows, index=starts)[["Common", "L_only", "R_only", "C_only"]]
    x_labels = [str(s) for s in starts]

    fig = go.Figure()

    fig.add_bar(x=x_labels, y=period_df["L_only"], name="Left only",
                marker_color=BAR_COLORS["L_only"], offsetgroup="exclusive", base=0)
    fig.add_bar(x=x_labels, y=period_df["C_only"], name="Center only",
                marker_color=BAR_COLORS["C_only"], offsetgroup="exclusive", base=period_df["L_only"])
    fig.add_bar(x=x_labels, y=period_df["R_only"], name="Right only",
                marker_color=BAR_COLORS["R_only"], offsetgroup="exclusive",
                base=period_df["L_only"] + period_df["C_only"])
    fig.add_bar(x=x_labels, y=period_df["Common"], name="Common",
                marker_color=BAR_COLORS["Common"], offsetgroup="common")

    fig.update_layout(
        title=f"Vocabulary by political spectrum (period-pooled, {topn_toggle.value})",
        xaxis=dict(title="Period start year", categoryorder="array", categoryarray=x_labels),
        yaxis=dict(title="# words"),
        barmode="group",
        template="plotly_white",
        autosize=True,
        height=PLOT_HEIGHT,
        margin=dict(t=60),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    )

    with output:
        output.clear_output(wait=True)
        fig.show()

topn_toggle.observe(redraw, names="value")

display(topn_toggle, output)
redraw()

Tokenizing and counting all periods/groups (this runs once)...
Done.


ToggleButtons(description='Vocab size:', options=('Top 1000', 'Top 10000'), value='Top 1000')

Output(layout=Layout(width='100%'))

In [22]:
top_n = top_n = TOP_N_OPTIONS[topn_toggle.value]  # matches whatever the toggle is currently set to
for s in get_periods(PERIOD_YEARS):
    print_period_words(s, top_n=top_n, top_n_print=20)

---- 1945-1949 ----
Right only:
(none)

Left only:
(none)

Center only:
potere dovere italiano volere popolo Italia venire partito libertà politico guerra esso dare sapere sociale bisognare pace amico economico questione

In Common:
(none)

---- 1950-1954 ----
Right only:
(none)

Left only:
(none)

Center only:
potere dovere Italia volere italiano popolo pace problema guerra venire esso comunista democrazia partito libertà politico Europa democratico sociale gaspere

In Common:
(none)

---- 1955-1959 ----
Right only:
(none)

Left only:
(none)

Center only:
(none)

In Common:
(none)

---- 1960-1964 ----
Right only:
(none)

Left only:
potere problema volere dovere italiano articolo dottore presidente sapere signore diritto ricordare pensione dare cittadino programma parlare elezione punto sindacato

Center only:
(none)

In Common:
(none)

---- 1965-1969 ----
Right only:
(none)

Left only:
(none)

Center only:
(none)

In Common:
(none)

---- 1970-1974 ----
Right only:
(none)

Left only:
(

In [23]:
from collections import Counter

def collect_global_ranked_words(top_n):
    """Collects every unique word appearing in any bar (L_only, R_only, C_only, Common)
    across all periods, deduplicated, ordered by total frequency across all
    period+group counters combined."""
    starts = get_periods(PERIOD_YEARS)

    seen_words = set()
    global_freq = Counter()

    for s in starts:
        breakdown = period_word_breakdown(s, top_n)
        sets = breakdown["_sets"]

        # union of everything currently shown across the four bars
        for bucket in ("L_only", "R_only", "C_only", "Common"):
            seen_words |= sets[bucket]

        # accumulate frequency from the underlying period counters,
        # regardless of which bucket the word landed in
        for g in ("L", "R", "C"):
            global_freq.update(PERIOD_COUNTERS[s][g])

    # keep only words that actually appear in at least one bar, ordered by total freq
    ranked = sorted(seen_words, key=lambda w: global_freq[w], reverse=True)
    return ranked

def print_global_word_list(top_n):
    ranked = collect_global_ranked_words(top_n)
    print(f"Total unique words across all periods/groups: {len(ranked)}")
    print(" ".join(ranked))

top_n = TOP_N_OPTIONS[topn_toggle.value]
print_global_word_list(top_n)

Total unique words across all periods/groups: 4749
potere dovere volere politico problema credere Italia andare stare politica partito vedere italiano venire Europa dare europeo sapere punto pensare parlare presidente sistema pubblico mettere diverso importante sinistra trovare tema legge vero portare democrazia senso mercato rispetto storia riforma democratico sociale ricordare arrivare economico questione forte cittadino rapporto idea prendere ragione impresa bisogno società chiedere diritto bisognare interesse libertà riuscire situazione cercare elettorale comune realtà parola sentire parlamento unico guardare economia condizione soprattutto processo possibile domanda interno capire creare internazionale sviluppo chiaro crisi riguardare cambiare fronte valore maggioranza fondo ritenere elezione difficile responsabilità lavorare cultura accordo scelta programma livello voto vista regione confronto conto possibilità giovane amico cominciare comunista maggiore particolare guerra istitu

#### Stopwords and lemmatization
Lemmatizing seem to improve a bit the output quality, at the expense of 50x computation time 

Without lemmatizing:
```bash
---- 1995-1999 ----
Right only:
comunisti disse senato senatore crediamo silvio imposte andreotti presentato magistratura monti affinché concezione regime chiesa aprile benessere moro succede giudice

Left only:
logica evidente donne sindacato centrosinistra rinnovamento allargamento popolari romano assieme mette rappresentanza serio trovo locale pone culturali terreno socialismo est

Center only:
tesoro cambio solamente titoli finanziarie spadolini bancario programmazione intero operatori prezzi monetario ciampi governatore redditi fondazioni attuazione fattori privatizzazioni superare

In Common:
politica credo problema italia europa cioè punto dobbiamo sistema diciamo partito paesi problemi cose politico europea rispetto senso grandi importante
```

With lemmatizing:
```bash
---- 1995-1999 ----
Right only:
senatore imposta silvio concezione magistrato magistratura affinché Andreotti chiesa regime avversario piazza dichiarare aprile benessere moro Maastricht sovietico stampa minoranza

Left only:
compagno logica rappresentanza allargamento centrosinistra immaginare collettivo missione assieme bambino ceto socialismo diversità bertinotto intesa affatto ricco novità polemica inutile

Center only:
cambio tesoro bancario solamente governatore spadolino emissione miglioramento credito attuazione operativo inferiore investitore pagamento luglio svalutazione accelerare azionista borsa perseguire

In Common:
potere dovere volere problema politico credere Italia stare andare politica Europa europeo punto vedere partito italiano dare venire pensare cioè
```

#### Top 1k VS Top 10k
Using top 10k dirties the outputs:

**Top 1k:**
```bash
---- 1995-1999 ----
Right only:
senatore imposta silvio magistrato magistratura Andreotti chiesa regime avversario piazza dichiarare aprile benessere moro Maastricht sovietico stampa minoranza lettera polizia

Left only:
compagno logica rappresentanza allargamento centrosinistra immaginare collettivo missione assieme bambino ceto socialismo diversità bertinotto intesa affatto ricco novità capitolo giornata

Center only:
tesoro bancario solamente governatore spadolino emissione miglioramento credito attuazione operativo inferiore investitore pagamento luglio svalutazione accelerare azionista borsa perseguire percentuale

In Common:
potere dovere volere problema politico credere Italia stare andare politica Europa europeo punto vedere partito italiano dare venire pensare sapere
```

**Top 10k**
```bash
---- 1995-1999 ----
Right only:
erario ferdinare pier rocco gladio albertino umanesimo sardo cerimoniale Muslim Forza innanzi liquota christian intergenerazionale teologia fanfano furto patriotismo piazzante

Left only:
popolarismo agio roba inesorabilmente ventesimo fetta diseguaglianza fordista ambientalista infanzia selezionare unilaterale maternità albero teorizzare costruare editoria congegno monopolista cofferare

Center only:
calogero redditività regolarità giornalmente Hazard avanso analogamente ceguto render salvatorello scanno privatizzato giardo allungamento autoregolamentazione prezzare moral vestimente oscillazione procapito

In Common:
potere dovere volere problema politico credere Italia stare andare politica Europa europeo punto vedere partito italiano dare venire pensare sapere
```

## t-SNE

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import ipywidgets as widgets
from sklearn.manifold import TSNE

OVERLAP_COLOR = "#000000"  

def load_vec_format(path, limit=500_000):
    """
    Minimal loader for fastText .vec files (word2vec text format).
    First line: '<num_words> <dim>', then one line per word: 'word v1 v2 ... vN'
    """
    vectors = {}
    with open(path, "r", encoding="utf-8", newline="\n", errors="ignore") as f:
        n_words, dim = map(int, f.readline().split())
        for i, line in enumerate(f):
            if i >= limit:
                break
            parts = line.rstrip().split(" ")
            word = parts[0]
            vectors[word] = np.asarray(parts[1:], dtype=np.float32)
    return vectors

embedding_model = load_vec_format("./embeddings/cc.it.300.vec", limit=500_000)      # fastText pretrained Italian word vectors (CBOW)

# -------------------------------------
# 1) Build a combined word-vector matrix across all politicians
#    ADAPT: point this at your embedding source
#    (word2vec/GloVe KeyedVectors, embedding_model[word], etc.)
# -------------------------------------
records = []  # (word, politician, vector)
for pol, words in politician_top1000.items():        # <-- dict: politician -> list[str]
    for w in words:
        if w in embedding_model:                # <-- your embedding lookup
            records.append((w, pol, embedding_model[w]))

words_arr = np.array([r[0] for r in records])
pols_arr  = np.array([r[1] for r in records])
vectors   = np.vstack([r[2] for r in records])

# -------------------------------------
# 2) Fit t-SNE ONCE in 2D and 3D over the full set
#    (keeps point positions stable as you toggle politicians on/off)
# -------------------------------------
coords2d = TSNE(n_components=2, init="pca", random_state=42, perplexity=30).fit_transform(vectors)
coords3d = TSNE(n_components=3, init="pca", random_state=42, perplexity=30).fit_transform(vectors)

tsne_df = pd.DataFrame({
    "word": words_arr, "politician": pols_arr,
    "x2": coords2d[:, 0], "y2": coords2d[:, 1],
    "x3": coords3d[:, 0], "y3": coords3d[:, 1], "z3": coords3d[:, 2],
})

# -------------------------------------
# 3) Checkbox grid (same pattern as MTLD dashboard)
# -------------------------------------
pol_names = list(politician_top1000.keys())
checkboxes = []
for pol in pol_names:
    cb = widgets.Checkbox(
        value=(pol in ["meloni", "degasperi"]),
        description=display_name(pol), indent=False,
        layout=widgets.Layout(width="180px"),
    )
    cb.pol_key = pol
    checkboxes.append(cb)

all_checkbox = widgets.Checkbox(value=False, description="All", indent=False,
                                 layout=widgets.Layout(width="180px"))

_syncing = False

def on_all_change(change):
    global _syncing
    if _syncing: return
    _syncing = True
    for cb in checkboxes:
        cb.value = change["new"]
    _syncing = False
    redraw()

def on_individual_change(change):
    global _syncing
    if _syncing: return
    _syncing = True
    all_checkbox.value = all(cb.value for cb in checkboxes)
    _syncing = False
    redraw()

all_checkbox.observe(on_all_change, names="value")
for cb in checkboxes:
    cb.observe(on_individual_change, names="value")

checkbox_grid = widgets.GridBox(
    [all_checkbox] + checkboxes,
    layout=widgets.Layout(width="100%", grid_template_columns="repeat(auto-fill, minmax(150px, 1fr))"),
)

# -------------------------------------
# 4) 2D / 3D toggle
# -------------------------------------
dim_toggle = widgets.ToggleButtons(options=["2D", "3D"], value="2D", description="View:")

title_label = widgets.HTML()
def _title_html(view):
    return (f"<h2 style='margin:12px 0 4px 0; font-family:sans-serif; text-align:center;'>"
            f"t-SNE Word Embedding Space — {view}</h2>")
title_label.value = _title_html(dim_toggle.value)

output = widgets.Output()

# -------------------------------------
# 5) Plot function
# -------------------------------------

# -------------------------------------
# Optional: dynamic blend instead of fixed OVERLAP_COLOR
# Averages the hex colors of whichever politicians share a given word.
# Uncomment build_shared_color() usage below to enable.
# -------------------------------------
def blend_hex_colors(hex_colors):
    rgbs = [tuple(int(c.lstrip("#")[i:i+2], 16) for i in (0, 2, 4)) for c in hex_colors]
    avg = tuple(int(sum(ch) / len(ch)) for ch in zip(*rgbs))
    return f"#{avg[0]:02x}{avg[1]:02x}{avg[2]:02x}"

# -------------------------------------
# Highlight toggle
# -------------------------------------
highlight_toggle = widgets.ToggleButtons(
    options=["On", "Off"], value="On", description="Highlight overlap:"
)


# -------------------------------------
# Updated plot function
# -------------------------------------
def plot_tsne(selected, view, highlight_overlap):
    fig = go.Figure()

    if highlight_overlap and len(selected) > 1:
        # count how many of the *selected* politicians used each word
        word_owners = {}
        for pol in selected:
            sub = tsne_df[tsne_df["politician"] == pol]
            for w in sub["word"]:
                word_owners.setdefault(w, set()).add(pol)

        shared_words = {w for w, owners in word_owners.items() if len(owners) > 1}
    else:
        shared_words = set()

    # ---------------------- DRAW POINTS -----------------------
    for pol in selected:
        sub = tsne_df[(tsne_df["politician"] == pol) & (~tsne_df["word"].isin(shared_words))]
        color = POL_INFO[pol]["color"]
        if view == "2D":
            fig.add_trace(go.Scatter(
                x=sub["x2"], y=sub["y2"], mode="markers",
                marker=dict(size=6, color=color),
                text=sub["word"], name=display_name(pol),
                hovertemplate="%{text}<extra>" + display_name(pol) + "</extra>",
            ))
        else:
            fig.add_trace(go.Scatter3d(
                x=sub["x3"], y=sub["y3"], z=sub["z3"], mode="markers",
                marker=dict(size=3, color=color),
                text=sub["word"], name=display_name(pol),
                hovertemplate="%{text}<extra>" + display_name(pol) + "</extra>",
            ))

    # one point per shared word, drawn last so it sits on top
    if shared_words:
        shared_sub = tsne_df[tsne_df["word"].isin(shared_words)].drop_duplicates(subset="word")
        if view == "2D":
            fig.add_trace(go.Scatter(
                x=shared_sub["x2"], y=shared_sub["y2"], mode="markers",
                marker=dict(size=6, color=OVERLAP_COLOR, symbol="diamond"),
                text=shared_sub["word"], name="Shared Vocabulary",
                hovertemplate="%{text}<extra>Shared</extra>",
            ))
        else:
            fig.add_trace(go.Scatter3d(
                x=shared_sub["x3"], y=shared_sub["y3"], z=shared_sub["z3"], mode="markers",
                marker=dict(size=1.5, color=OVERLAP_COLOR, symbol="diamond"),
                text=shared_sub["word"], name="Shared Vocabulary",
                hovertemplate="%{text}<extra>Shared</extra>",
            ))

    fig.update_layout(
        #width=850, 
        height=750,
        autosize=True,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="center", x=0.5),
        margin=dict(l=20, r=20, t=40, b=20),
    )
    if view == "3D":
        fig.update_layout(scene=dict(xaxis_title="", yaxis_title="", zaxis_title=""))
    else:
        fig.update_layout(xaxis_title="", yaxis_title="")
    fig.show(config={"responsive":True})

# -------------------------------------
# Redraw wiring — add highlight_toggle to observers + display
# -------------------------------------
def redraw(change=None):
    selected = [cb.pol_key for cb in checkboxes if cb.value]
    title_label.value = _title_html(dim_toggle.value)
    with output:
        output.clear_output(wait=True)
        plot_tsne(selected, dim_toggle.value, highlight_toggle.value == "On")

dim_toggle.observe(redraw, names="value")
highlight_toggle.observe(redraw, names="value")

display(checkbox_grid, dim_toggle, highlight_toggle, title_label, output)
redraw()

KeyboardInterrupt: 

In [ ]:
"""
export_data.py

Builds data.json for the static t-SNE word-embedding page (index.html),
from the same inputs used in the notebook version of the crossdem
t-SNE visualization.

Usage:
    python export_data.py

Adapt the CONFIG section below to your own paths / data structures,
same as you did for export_data.py on the MTLD dashboard.
"""

import json
import colorsys

import numpy as np
from sklearn.manifold import TSNE

# ------------------------------------------------------------------
# CONFIG — adapt these to your project
# ------------------------------------------------------------------
EMBEDDINGS_PATH = "./embeddings/cc.it.300.vec"
EMBEDDINGS_LIMIT = 500_000
OUTPUT_PATH = f"{BASE_DIR}/docs/tsne/data.json"

# politician -> list[str] of their top-1000 words.
# Load this however you already build it in the notebook (e.g. read
# back from a CSV/pickle produced earlier in the crossdem pipeline)
# instead of hardcoding it here.
#
# Example:
#   import pandas as pd
#   top1000_df = pd.read_csv("top1000_words.csv")  # columns: politician, word
#   POLITICIAN_TOP1000 = (
#       top1000_df.groupby("politician")["word"].apply(list).to_dict()
#   )
POLITICIAN_TOP1000 = politician_top1000

# politician -> hex color. Reuse the same POL_COLORS dict you already
# use in the MTLD dashboard / notebook so colors stay consistent
# across visualizations.
#POL_COLORS = POL_COLORS

TSNE_PERPLEXITY = 30
RANDOM_STATE = 42


def load_vec_format(path, limit=500_000):
    """
    Minimal loader for fastText .vec files (word2vec text format).
    First line: '<num_words> <dim>', then one line per word: 'word v1 v2 ... vN'
    """
    vectors = {}
    with open(path, "r", encoding="utf-8", newline="\n", errors="ignore") as f:
        n_words, dim = map(int, f.readline().split())
        for i, line in enumerate(f):
            if i >= limit:
                break
            parts = line.rstrip().split(" ")
            word = parts[0]
            vectors[word] = np.asarray(parts[1:], dtype=np.float32)
    return vectors


def default_color(i, n):
    """Fallback rainbow-ish palette for any politician missing from POL_COLORS."""
    h = i / max(n, 1)
    r, g, b = colorsys.hsv_to_rgb(h, 0.55, 0.85)
    return f"#{int(r * 255):02x}{int(g * 255):02x}{int(b * 255):02x}"


def main():
    if not POLITICIAN_TOP1000:
        raise RuntimeError(
            "POLITICIAN_TOP1000 is empty — fill it in (or load it from your "
            "existing top-1000-words file) before running this script."
        )

    print(f"Loading embeddings from {EMBEDDINGS_PATH} ...")
    embedding_model = load_vec_format(EMBEDDINGS_PATH, limit=EMBEDDINGS_LIMIT)
    print(f"Loaded {len(embedding_model)} vectors.")

    records = []  # (word, politician, vector)
    for pol, words in POLITICIAN_TOP1000.items():
        for w in words:
            if w in embedding_model:
                records.append((w, pol, embedding_model[w]))

    if not records:
        raise RuntimeError(
            "No (word, politician) records found — check POLITICIAN_TOP1000 "
            "and that its words actually appear in the embedding vocabulary."
        )

    words_arr = np.array([r[0] for r in records])
    pols_arr = np.array([r[1] for r in records])
    vectors = np.vstack([r[2] for r in records])

    print(f"Fitting t-SNE (2D) over {len(records)} points ...")
    coords2d = TSNE(
        n_components=2, init="pca", random_state=RANDOM_STATE,
        perplexity=TSNE_PERPLEXITY,
    ).fit_transform(vectors)

    print(f"Fitting t-SNE (3D) over {len(records)} points ...")
    coords3d = TSNE(
        n_components=3, init="pca", random_state=RANDOM_STATE,
        perplexity=TSNE_PERPLEXITY,
    ).fit_transform(vectors)

    politicians = list(POLITICIAN_TOP1000.keys())
    colors = {
        pol: POL_COLORS.get(pol, default_color(i, len(politicians)))
        for i, pol in enumerate(politicians)
    }

    points = []
    for i in range(len(records)):
        points.append({
            "word": words_arr[i],
            "politician": pols_arr[i],
            "x2": round(float(coords2d[i, 0]), 4),
            "y2": round(float(coords2d[i, 1]), 4),
            "x3": round(float(coords3d[i, 0]), 4),
            "y3": round(float(coords3d[i, 1]), 4),
            "z3": round(float(coords3d[i, 2]), 4),
        })

    data = {
        "politicians": politicians,
        "colors": colors,
        "points": points,
    }

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False)

    print(f"Wrote {len(points)} points for {len(politicians)} politicians to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()

Loading embeddings from ./embeddings/cc.it.300.vec ...
Loaded 500000 vectors.
Fitting t-SNE (2D) over 23913 points ...
Fitting t-SNE (3D) over 23913 points ...
Wrote 23913 points for 25 politicians to /home/mhetac/Documents/GitHub/crossdem/docs/tsne/data.json


#### Meloni Degas

In [ ]:
if False:    
    import numpy as np
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.manifold import TSNE

    # --- CONFIGURATION CONSTANTS ---
    MAX_LABELS = 80  # Total maximum number of data points that get a label
    # -------------------------------

    # 1. Define your corpus properly
    degasperi_full_text = " ".join(degasperi_words)
    meloni_full_text = " ".join(meloni_words)
    corpus = [degasperi_full_text, meloni_full_text]

    # 2. Get the unique set of your top 1000 words from both speakers
    combined_top_words = list(top1000_degasperi.union(top1000_meloni))

    # 3. Vectorize ONLY your top words
    vectorizer = TfidfVectorizer(vocabulary=combined_top_words)
    X = vectorizer.fit_transform(corpus)
    word_vectors = X.T.toarray()

    # 4. Reduce dimensions to 2D using t-SNE
    tsne = TSNE(n_components=2, perplexity=5, random_state=42, init='random')
    word_coords = tsne.fit_transform(word_vectors)

    # 5. Determine colors for ALL dots based on ownership
    dot_colors = []
    for word in combined_top_words:
        if word in top1000_degasperi and word in top1000_meloni:
            dot_colors.append('#8A2BE2')  # Purple (Shared)
        elif word in top1000_degasperi:
            dot_colors.append('#4A90D9')  # Blue (De Gasperi)
        else:
            dot_colors.append('#E8534A')  # Red (Meloni)

    # 6. Define which words get labeled using MAX_LABELS
    half_max = MAX_LABELS // 2
    words_to_label = list(top1000_degasperi)[:half_max] + list(top1000_meloni)[:half_max]

    # 7. Plot the graphical view
    plt.figure(figsize=(28, 20))

    # Plot all dots with their respective ownership colors
    plt.scatter(
        word_coords[:, 0], word_coords[:, 1],
        alpha=1,
        c=dot_colors,
        edgecolors='w',
        linewidth=0.5,
        s=90  # dot size
    )

    # Annotate the subset of words
    for i, word in enumerate(combined_top_words):
        if word in words_to_label:
            label_color = dot_colors[i]
            # plt.annotate(
            #     word,
            #     (word_coords[i, 0], word_coords[i, 1]),
            #     xytext=(5, 2),
            #     textcoords='offset points',
            #     fontsize=8,
            #     color='black',
            #     weight='normal'
            # )

    # Legend via proxy artists
    legend_handles = [
        mpatches.Patch(color='#4A90D9', label='De Gasperi Exclusive Vocabulary'),
        mpatches.Patch(color='#E8534A', label='Meloni Exclusive Vocabulary'),
        mpatches.Patch(color='#8A2BE2', label='Shared Vocabulary'),
    ]
    plt.legend(handles=legend_handles, fontsize=20, loc='best')
    plt.title("Word Vector Space (t-SNE) — Comparing the Vocabularies of De Gasperi and Meloni", fontsize=24)
    plt.grid(True, linestyle='--', alpha=0.3)
    plt.savefig("tsne_melonidegasperi.png", dpi=300)
    plt.show()


# Sentiment Analysis

## Type Of Architecture Choice

Encoder-Decoder models are often trained on Twitter corpus -> dont perform well on political speeches.
Also BERT cannot handle more than 512 tokens in one go, I have avg 2k token per speech.

My data is *unlabelled*, therefore a model like BERT which relies a lot on fine-tuning is not the right choice. On the other hand, decoder only models don't need this phase at all.

Oss: LLMs are bad ad continuous scales, better to as for score between 1 and 5.



## Find High Negativity Examples

In [ ]:
"""
find_hate_negativity_candidates.py

Lexicon-based triage over the full ~6k-speech corpus (PMS_DIR) to surface
candidate speeches worth hand-labeling, instead of hand-labeling at random.

Scores every already-scraped speech (PMS_DIR/{politician}/csv_out/*.csv) for:
  - negativity: density of negative-sentiment lemmas
  - hate_speech: density of sentences where an ethnic/religious/gender GROUP
                 term co-occurs with a HOSTILITY term (same sentence)

Copies the top N speeches per dimension (raw CSV files, unmodified, exactly
as they exist in csv_out/) into VALIDATION_DIR/{politician}/, so you only
need to hand-label a small, high-yield pool instead of the full corpus.

IMPORTANT — read before trusting the output:
- This is a coarse triage filter, not a hate-speech detector. The lexicons
  below are small seed lists I wrote quickly. They WILL miss things, and
  they WILL surface false positives — e.g. a speech *condemning* xenophobia
  mentions both a group term and a hostility term in the same sentence and
  will score just as high as a speech being hostile itself. You still need
  to read and hand-label whatever gets copied here; this step only improves
  which 15+15 speeches you spend that time on.
- For something more validated than a hand-typed seed list, look at HurtLex
  (Bassignana et al.) — an academically-vetted Italian hostility lexicon —
  as a drop-in replacement for HOSTILITY_LEMMAS.
- Speeches already present in VALIDATION_DIR/{politician}/ are excluded from
  candidacy so you don't re-flag something already labeled.

Requires BASE_DIR / PMS_DIR / VALIDATION_DIR / POL_INFO already in scope
(from your crossdem setup cell).

Install deps:
    pip install spacy pandas tqdm --break-system-packages
    python -m spacy download it_core_news_sm
"""

import os
import glob
import shutil
from pathlib import Path

import pandas as pd
import spacy
from tqdm import tqdm

TEXT_COL = "text"   # <-- CHECK: should match TEXT_COL in compare_llm_classifiers.py
TOP_N = 15

CACHE_DIR = Path(os.path.join(BASE_DIR, "source/pred_cache"))
os.makedirs(CACHE_DIR, exist_ok=True)

# --------------------------------------------------------------------------- #
# Seed lexicons — small starting point, extend/replace as needed
# --------------------------------------------------------------------------- #

NEGATIVITY_LEMMAS = {
    "crisi", "fallimento", "pericolo", "minaccia", "nemico", "corruzione",
    "disastro", "vergogna", "tradimento", "odio", "violenza", "morte", "guerra",
    "catastrofe", "degrado", "declino", "sconfitta", "ingiustizia", "povertà",
    "disoccupazione", "insicurezza", "paura", "terrore", "allarme", "emergenza",
    "scandalo", "illegalità", "criminalità", "invasione", "distruzione",
    "rovina", "collasso", "disperazione", "indignazione", "rabbia", "inganno",
    "menzogna", "bugia", "ipocrisia", "colpa", "condanna", "attacco", "conflitto",
}

# group-reference terms — deliberately neutral/descriptive, not slurs
GROUP_LEMMAS = {
    "immigrato", "straniero", "migrante", "rom", "sinto", "africano", "arabo",
    "cinese", "albanese", "rumeno", "nero",
    "musulmano", "islamico", "ebreo",
    "donna", "omosessuale", "gay", "lesbica", "transgender",
}

HOSTILITY_LEMMAS = {
    "invasione", "minaccia", "pericolo", "criminale", "delinquente", "clandestino",
    "cacciare", "espellere", "rimandare", "inferiore", "sporco", "sporcare",
    "nemico", "invadere", "aggredire", "delinquere",
}

# --------------------------------------------------------------------------- #

print("Loading spaCy model...")
nlp = spacy.load("it_core_news_sm", disable=["ner", "parser"])
nlp.add_pipe("sentencizer")


def score_text(doc) -> dict:
    n_tokens = len(doc)
    if n_tokens == 0:
        return {"negativity_score": 0.0, "hate_score": 0.0, "n_tokens": 0}

    neg_hits = sum(1 for tok in doc if tok.lemma_.lower() in NEGATIVITY_LEMMAS)
    negativity_score = 1000 * neg_hits / n_tokens

    hate_sentence_hits = 0
    n_sents = 0
    for sent in doc.sents:
        n_sents += 1
        lemmas = {tok.lemma_.lower() for tok in sent}
        if lemmas & GROUP_LEMMAS and lemmas & HOSTILITY_LEMMAS:
            hate_sentence_hits += 1
    hate_score = 1000 * hate_sentence_hits / max(n_sents, 1)

    return {"negativity_score": negativity_score, "hate_score": hate_score, "n_tokens": n_tokens}


def collect_candidate_files() -> list:
    """Every scraped speech file not already sitting in VALIDATION_DIR/{pol}/."""
    candidates = []
    for pol in POL_INFO:
        pol_dir = os.path.join(PMS_DIR, pol, "csv_out")
        files = glob.glob(os.path.join(pol_dir, "*.csv"))
        if not files:
            continue  # e.g. degasperi, which has no per-speech csv_out files

        dest_dir = os.path.join(VALIDATION_DIR, pol)
        os.makedirs(dest_dir, exist_ok=True)
        already_validated = {Path(f).name for f in glob.glob(os.path.join(dest_dir, "*.csv"))}

        for f in files:
            if Path(f).name in already_validated:
                continue
            candidates.append({"politician": pol, "filepath": f})
    return candidates


def copy_to_validation(df: pd.DataFrame, dimension: str):
    for _, row in df.iterrows():
        src = Path(row["filepath"])
        dest_dir = Path(VALIDATION_DIR) / row["politician"]
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest = dest_dir / src.name
        if dest.exists():
            print(f"  [{dimension}] already present, skipping: {dest}")
            continue
        shutil.copy2(src, dest)
        print(f"  [{dimension}] copied {src.name} -> {dest_dir}")


def main():
    candidates = collect_candidate_files()
    print(f"Found {len(candidates)} candidate speeches not already in VALIDATION_DIR.")

    texts = []
    valid_candidates = []
    for c in candidates:
        try:
            row = pd.read_csv(c["filepath"]).iloc[0]
        except Exception as e:
            print(f"  skipping {c['filepath']}: {e}")
            continue
        if TEXT_COL not in row or not isinstance(row[TEXT_COL], str):
            continue
        texts.append(row[TEXT_COL])
        valid_candidates.append(c)

    print(f"Scoring {len(valid_candidates)} speeches (this can take a few minutes for ~5k speeches)...")
    for c, doc in tqdm(zip(valid_candidates, nlp.pipe(texts, batch_size=32)), total=len(valid_candidates)):
        c.update(score_text(doc))

    scores_df = pd.DataFrame(valid_candidates)
    scores_path = CACHE_DIR / "candidate_scores.csv"
    scores_df.to_csv(scores_path, index=False)
    print(f"Full ranking (all {len(scores_df)} candidates) saved to {scores_path}")

    top_negativity = scores_df.sort_values("negativity_score", ascending=False).head(TOP_N)
    top_hate = scores_df.sort_values("hate_score", ascending=False).head(TOP_N)

    print(f"\nTop {TOP_N} negativity candidates:")
    print(top_negativity[["politician", "filepath", "negativity_score", "n_tokens"]].to_string(index=False))

    print(f"\nTop {TOP_N} hate_speech candidates:")
    print(top_hate[["politician", "filepath", "hate_score", "n_tokens"]].to_string(index=False))

    copy_to_validation(top_negativity, "negativity")
    copy_to_validation(top_hate, "hate_speech")


if __name__ == "__main__":
    pass
    #main()

Loading spaCy model...
Found 5465 candidate speeches not already in VALIDATION_DIR.
Scoring 5464 speeches (this can take a few minutes for ~5k speeches)...


100%|██████████| 5464/5464 [07:24<00:00, 12.30it/s]

Full ranking (all 5464 candidates) saved to /home/mhetac/Documents/GitHub/crossdem/source/pred_cache/candidate_scores.csv

Top 15 negativity candidates:
politician                                                                                                    filepath  negativity_score  n_tokens
      dini            /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/dini/csv_out/314276_dini_s2t.csv         37.500000       160
     letta          /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/letta/csv_out/118109_letta_s2t.csv         26.490066       151
 andreotti  /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/andreotti/csv_out/222504_andreotti_s2t.csv         22.598870       177
   d'alema       /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/d'alema/csv_out/264004_dalema_s2t.csv         22.222222       225
     prodi          /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/prodi/csv_out/119887_prodi_s

Output: 

```bash
Loading spaCy model...
Found 5465 candidate speeches not already in VALIDATION_DIR.
Scoring 5464 speeches (this can take a few minutes for ~5k speeches)...
100%|██████████| 5464/5464 [07:24<00:00, 12.30it/s]Full ranking (all 5464 candidates) saved to /home/mhetac/Documents/GitHub/crossdem/source/pred_cache/candidate_scores.csv

Top 15 negativity candidates:
politician                                                                                                    filepath  negativity_score  n_tokens
      dini            /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/dini/csv_out/314276_dini_s2t.csv         37.500000       160
     letta          /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/letta/csv_out/118109_letta_s2t.csv         26.490066       151
 andreotti  /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/andreotti/csv_out/222504_andreotti_s2t.csv         22.598870       177
   d'alema       /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/d'alema/csv_out/264004_dalema_s2t.csv         22.222222       225
     prodi          /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/prodi/csv_out/119887_prodi_s2t.csv         21.782178       505
     prodi          /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/prodi/csv_out/219002_prodi_s2t.csv         19.607843        51
    meloni /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/meloni/csv_out/sMzNn_meloni_speech2text.csv         18.599562       914
     letta          /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/letta/csv_out/161521_letta_s2t.csv         18.255578       493
   d'alema       /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/d'alema/csv_out/134219_dalema_s2t.csv         17.994859       389
   d'alema       /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/d'alema/csv_out/211407_dalema_s2t.csv         17.490494      2630
 andreotti  /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/andreotti/csv_out/158786_andreotti_s2t.csv         17.139090      1517
   d'alema       /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/d'alema/csv_out/203971_dalema_s2t.csv         16.806723       238
     renzi          /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/renzi/csv_out/433686_renzi_s2t.csv         16.233766       308
 andreotti  /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/andreotti/csv_out/223670_andreotti_s2t.csv         15.904573       503
   d'alema       /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/d'alema/csv_out/149151_dalema_s2t.csv         15.846258      2966

Top 15 hate_speech candidates:
politician                                                                                                     filepath  hate_score  n_tokens
     amato           /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/amato/csv_out/136189_amato_s2t.csv      1000.0      2797
     amato           /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/amato/csv_out/204629_amato_s2t.csv      1000.0      2062
     amato           /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/amato/csv_out/137542_amato_s2t.csv      1000.0      5747
   d'alema        /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/d'alema/csv_out/655295_dalema_s2t.csv      1000.0      1999
berlusconi /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/berlusconi/csv_out/156460_berlusconi_s2t.csv      1000.0      5765
    meloni         /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/meloni/csv_out/217051_meloni_s2t.csv      1000.0      2708
berlusconi /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/berlusconi/csv_out/228170_berlusconi_s2t.csv      1000.0      1314
berlusconi /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/berlusconi/csv_out/204646_berlusconi_s2t.csv      1000.0      7892
     letta           /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/letta/csv_out/319099_letta_s2t.csv      1000.0      2639
    meloni         /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/meloni/csv_out/331612_meloni_s2t.csv      1000.0      3072
    meloni         /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/meloni/csv_out/316761_meloni_s2t.csv      1000.0      1258
 andreotti   /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/andreotti/csv_out/245886_andreotti_s2t.csv      1000.0      3891
     monti           /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/monti/csv_out/144957_monti_s2t.csv      1000.0      2308
     amato           /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/amato/csv_out/257502_amato_s2t.csv      1000.0      5687
     amato           /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers/amato/csv_out/456686_amato_s2t.csv      1000.0      1953
  [negativity] copied 314276_dini_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/dini
  [negativity] copied 118109_letta_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/letta
  [negativity] copied 222504_andreotti_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/andreotti
  [negativity] copied 264004_dalema_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/d'alema
  [negativity] copied 119887_prodi_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/prodi
  [negativity] copied 219002_prodi_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/prodi
  [negativity] copied sMzNn_meloni_speech2text.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/meloni
  [negativity] copied 161521_letta_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/letta
  [negativity] copied 134219_dalema_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/d'alema
  [negativity] copied 211407_dalema_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/d'alema
  [negativity] copied 158786_andreotti_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/andreotti
  [negativity] copied 203971_dalema_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/d'alema
  [negativity] copied 433686_renzi_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/renzi
  [negativity] copied 223670_andreotti_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/andreotti
  [negativity] copied 149151_dalema_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/d'alema
  [hate_speech] copied 136189_amato_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/amato
  [hate_speech] copied 204629_amato_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/amato
  [hate_speech] copied 137542_amato_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/amato
  [hate_speech] copied 655295_dalema_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/d'alema
  [hate_speech] copied 156460_berlusconi_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/berlusconi
  [hate_speech] copied 217051_meloni_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/meloni
  [hate_speech] copied 228170_berlusconi_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/berlusconi
  [hate_speech] copied 204646_berlusconi_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/berlusconi
  [hate_speech] copied 319099_letta_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/letta
  [hate_speech] copied 331612_meloni_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/meloni
  [hate_speech] copied 316761_meloni_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/meloni
  [hate_speech] copied 245886_andreotti_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/andreotti
  [hate_speech] copied 144957_monti_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/monti
  [hate_speech] copied 257502_amato_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/amato
  [hate_speech] copied 456686_amato_s2t.csv -> /home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/amato
```

## Evaluate Mistral VS Qwent

In [8]:
POL_VAL = [
    "degasperi",     
    "andreotti",    
    "amato",         
    "berlusconi",    
    "dini",          
    "prodi",         
    "dalema",        
    "monti",         
    "letta",         
    "renzi",         
    "meloni"       
]

VALIDATION_FILES = []

for pol in POL_VAL:
    speeches = glob.glob(f"{VALIDATION_DIR}/{pol}/*.csv")
    for speech in speeches:
        VALIDATION_FILES.append(speech)

for r in VALIDATION_FILES:
    print(r)

/home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/degasperi/degasperi_validation.csv
/home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/andreotti/158786_andreotti_s2t.csv
/home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/andreotti/222504_andreotti_s2t.csv
/home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/andreotti/223670_andreotti_s2t.csv
/home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/andreotti/245886_andreotti_s2t.csv
/home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/amato/136189_amato_s2t.csv
/home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/amato/137542_amato_s2t.csv
/home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/amato/204629_amato_s2t.csv
/home/mhetac/Documents/GitHub/crossdem/datasets/prime_ministers_validation/amato/257502_amato_s2t.csv
/home/mhetac/Documents/GitHub/crossdem/dat

In [ ]:
"""
compare_llm_classifiers.py

Compares mistralai/Mistral-7B-Instruct-v0.3 vs Qwen/Qwen2.5-7B-Instruct (both run
locally via Ollama, quantized) on the crossdem 4-label classification task:

    hate_speech     : low | mid | high
    negativity      : low | mid | high
    aggressiveness  : low | mid | high
    target          : none | pol_adv | minor_etn | minor_gnd | minor_rel

Validation set = your 100 hand-labeled speeches (degasperi_validation.csv +
meloni_validation.csv).

Assumes BASE_DIR / VALIDATION_DIR are already defined in your environment
(e.g. from your crossdem setup cell/module) before this script/cell runs.

Design notes:
- Uses Ollama's JSON-schema `format` param for grammar-constrained decoding, same
  spirit as your existing Qwen/llama.cpp pipeline.
- Predictions are cached to CSV incrementally (one API call = one row appended),
  so an interrupted run resumes instead of re-classifying from scratch.
- temperature=0 for reproducibility.
- VERBOSE=True prints, for every call: the row id, the text fed to the model,
  the raw model output, and the parsed prediction.

REQUIRES YOU TO CHECK / EDIT:
1. TEXT_COL, ID_COL below.
2. OLLAMA model tags — verify with `ollama list`.
3. The RUBRIC text in SYSTEM_PROMPT should match your manual annotation rubric.

Install deps:
    pip install ollama scikit-learn pandas
"""

import os
import json
import time
from pathlib import Path

import pandas as pd
from ollama import Client
from sklearn.metrics import (
    cohen_kappa_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix,
)

# --------------------------------------------------------------------------- #
# CONFIG — check this section before running
# --------------------------------------------------------------------------- #
POL_VAL = [
    "degasperi",     
    "andreotti",    
    "amato",         
    "berlusconi",    
    "dini",          
    "prodi",         
    "dalema",        
    "monti",         
    "letta",         
    "renzi",         
    "meloni"
]

VALIDATION_FILES = []

for pol in POL_VAL:
    speeches = glob.glob(f"{VALIDATION_DIR}/{pol}/*.csv")
    for speech in speeches:
        VALIDATION_FILES.append(speech)


TEXT_COL = "text"          # <-- CHECK: column holding the speech transcript
ID_COL = None               # <-- CHECK: unique id column, or leave None to use row index

ORDINAL_COLS = ["hate_speech", "negativity", "aggressiveness"]
NOMINAL_COLS = ["target"]
ALL_LABEL_COLS = ORDINAL_COLS + NOMINAL_COLS  # also the fixed output order for the pred lists

LEVEL_VALUES = ["low", "mid", "high"]
TARGET_VALUES = ["none", "pol_adv", "minor_etn", "minor_gnd", "minor_rel"]

# 4 bit quantization
OLLAMA_MODELS = {
    "qwen2.5-7b": "qwen2.5:7b-instruct-q4_K_M",       # <-- CHECK exact local tag
    "mistral-7b-v0.3": "mistral:7b-instruct-v0.3-q4_K_M",  # <-- CHECK exact local tag
}

CACHE_DIR = Path(os.path.join(BASE_DIR, "source/pred_cache"))
os.makedirs(CACHE_DIR, exist_ok=True)

RETRIES = 3
RETRY_SLEEP_S = 2

# --- verbosity ---
VERBOSE = True
PRINT_TEXT_CHARS = 400  # set to None to print the full speech text every call

client = Client()  # assumes `ollama serve` is running locally

# --------------------------------------------------------------------------- #
# PROMPT — align this with your manual annotation rubric
# --------------------------------------------------------------------------- #

SYSTEM_PROMPT = """Sei un annotatore esperto di scienze politiche e linguistica computazionale.
Il tuo compito è classificare un discorso pronunciato da un Presidente del Consiglio
italiano secondo quattro dimensioni.

1) hate_speech: presenza di incitamento all'odio verso individui o gruppi.
   - low: assente o non significativa
   - mid: presente in forma velata, allusiva o isolata
   - high: presente in forma esplicita, ripetuta o centrale nel discorso

2) negativity: tono complessivo negativo del discorso (critica, pessimismo, minacce percepite).
   - low: tono prevalentemente neutro o positivo
   - mid: presenza moderata di toni negativi o critici
   - high: tono prevalentemente o fortemente negativo

3) aggressiveness: aggressività verbale, toni polemici o ostili verso interlocutori/avversari.
   - low: tono pacato, istituzionale
   - mid: presenza moderata di polemica o ostilità
   - high: tono marcatamente polemico, ostile o conflittuale

4) target: il bersaglio principale di eventuale ostilità/critica nel discorso (indipendente
   dai punteggi sopra: assegna il target anche se hate_speech/negativity/aggressiveness sono "low").
   - none: nessun bersaglio specifico
   - pol_adv: avversari politici, partiti, altre istituzioni politiche
   - minor_etn: minoranze etniche (es. persone nere, immigrati di specifiche etnie)
   - minor_gnd: minoranze di genere (es. donne, comunità LGBT)
   - minor_rel: minoranze religiose (es. musulmani, ebrei)

Rispondi ESCLUSIVAMENTE con un oggetto JSON con queste quattro chiavi, senza testo
aggiuntivo, markdown o spiegazioni."""

JSON_SCHEMA = {
    "type": "object",
    "properties": {
        "hate_speech": {"type": "string", "enum": LEVEL_VALUES},
        "negativity": {"type": "string", "enum": LEVEL_VALUES},
        "aggressiveness": {"type": "string", "enum": LEVEL_VALUES},
        "target": {"type": "string", "enum": TARGET_VALUES},
    },
    "required": ["hate_speech", "negativity", "aggressiveness", "target"],
}


# --------------------------------------------------------------------------- #
# Data loading
# --------------------------------------------------------------------------- #

def load_validation_data() -> pd.DataFrame:
    dfs = [pd.read_csv(f) for f in VALIDATION_FILES]
    df = pd.concat(dfs, ignore_index=True)

    print(f"Loaded {len(df)} validation speeches. Columns: {df.columns.tolist()}")

    missing = [c for c in ALL_LABEL_COLS if c not in df.columns]
    if missing:
        raise ValueError(
            f"Gold label columns missing from validation CSVs: {missing}. "
            f"Available columns: {df.columns.tolist()}"
        )
    if TEXT_COL not in df.columns:
        raise ValueError(
            f"TEXT_COL='{TEXT_COL}' not found. Available columns: {df.columns.tolist()}"
        )

    if ID_COL is None:
        df = df.reset_index(drop=True)
        df["_row_id"] = df.index.astype(str)
    else:
        df["_row_id"] = df[ID_COL].astype(str)

    return df


# --------------------------------------------------------------------------- #
# Classification
# --------------------------------------------------------------------------- #

def classify_one(text: str, model_tag: str, row_id: str) -> dict | None:
    for attempt in range(1, RETRIES + 1):
        if VERBOSE:
            preview = text if PRINT_TEXT_CHARS is None else text[:PRINT_TEXT_CHARS]
            truncated_note = "" if PRINT_TEXT_CHARS is None or len(text) <= PRINT_TEXT_CHARS else " [truncated]"
            print(f"\n{'=' * 80}")
            print(f"[{model_tag}] row_id={row_id}  attempt {attempt}/{RETRIES}")
            print(f"--- PROMPT FED TO MODEL ({len(text)} chars{truncated_note}) ---")
            print(preview)

        try:
            resp = client.chat(
                model=model_tag,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": text},
                ],
                format=JSON_SCHEMA,
                options={"temperature": 0},
            )
            raw = resp["message"]["content"]

            if VERBOSE:
                print(f"--- RAW MODEL OUTPUT ---\n{raw}")

            parsed = json.loads(raw)
            # validate values are in-range; raises if not
            assert parsed["hate_speech"] in LEVEL_VALUES
            assert parsed["negativity"] in LEVEL_VALUES
            assert parsed["aggressiveness"] in LEVEL_VALUES
            assert parsed["target"] in TARGET_VALUES

            if VERBOSE:
                print(f"--- PARSED PREDICTION --- {parsed}")

            return parsed
        except Exception as e:
            print(f"  [{model_tag}] row_id={row_id} attempt {attempt}/{RETRIES} failed: {e}")
            time.sleep(RETRY_SLEEP_S)
    return None


def run_model(model_name: str, model_tag: str, df: pd.DataFrame) -> pd.DataFrame:
    cache_path = Path(f"{CACHE_DIR}/{model_name}_predictions.csv")

    if cache_path.exists():
        cached = pd.read_csv(cache_path, dtype={"_row_id": str})
        done_ids = set(cached["_row_id"])
    else:
        cached = pd.DataFrame(columns=["_row_id"] + ALL_LABEL_COLS)
        done_ids = set()

    rows_to_do = df[~df["_row_id"].isin(done_ids)]
    print(f"\n[{model_name}] {len(done_ids)} cached, {len(rows_to_do)} to classify.")

    new_rows = []
    for i, row in rows_to_do.iterrows():

        # RUN MODEL
        result = classify_one(row[TEXT_COL], model_tag, row["_row_id"])
        print(f"--- GOLD LABELS ---       {{'hate_speech': '{row['hate_speech']}', 'negativity': '{row['negativity']}', 'aggressiveness': '{row['aggressiveness']}', 'target': '{row['target']}'}}")

        if result is None:
            print(f"  [{model_name}] giving up on row {row['_row_id']} after {RETRIES} retries.")
            continue
        result["_row_id"] = row["_row_id"]
        new_rows.append(result)

        # append incrementally so a crash doesn't lose progress
        pd.DataFrame([result]).to_csv(
            cache_path, mode="a", header=not cache_path.exists(), index=False
        )

    if new_rows:
        cached = pd.concat([cached, pd.DataFrame(new_rows)], ignore_index=True)

    return cached


# --------------------------------------------------------------------------- #
# Predictions as a plain dict of lists
# --------------------------------------------------------------------------- #

def build_prediction_lists(pred_df: pd.DataFrame) -> list:
    """
    Turns a predictions dataframe into a plain list of
    [hate_speech, negativity, aggressiveness, target] lists,
    ordered by _row_id (numeric order if row ids are numeric, else lexicographic).

    Example output for one model:
        [
            ["low", "low", "low", "none"],
            ["low", "mid", "low", "none"],
            ...
        ]
    """
    df_sorted = pred_df.copy()
    try:
        df_sorted["_sort_key"] = df_sorted["_row_id"].astype(int)
    except ValueError:
        df_sorted["_sort_key"] = df_sorted["_row_id"]
    df_sorted = df_sorted.sort_values("_sort_key")
    return df_sorted[ALL_LABEL_COLS].values.tolist()


# --------------------------------------------------------------------------- #
# Metrics
# --------------------------------------------------------------------------- #

def evaluate(gold: pd.DataFrame, pred: pd.DataFrame, model_name: str) -> dict:
    merged = gold.merge(pred, on="_row_id", suffixes=("_gold", "_pred"))
    print(f"\n=== {model_name}: evaluated on {len(merged)}/{len(gold)} speeches ===")

    results = {}
    for col in ALL_LABEL_COLS:
        y_true = merged[f"{col}_gold"]
        y_pred = merged[f"{col}_pred"]

        weights = "quadratic" if col in ORDINAL_COLS else None
        kappa = cohen_kappa_score(y_true, y_pred, weights=weights)

        precision, recall, f1, _ = precision_recall_fscore_support(
            y_true, y_pred, average="macro", zero_division=0
        )
        acc = (y_true == y_pred).mean()

        results[col] = {
            "cohen_kappa": kappa,
            "accuracy": acc,
            "macro_precision": precision,
            "macro_recall": recall,
            "macro_f1": f1,
        }

        print(f"\n--- {col} ---")
        print(f"  Cohen's kappa ({'quadratic-weighted' if weights else 'unweighted'}): {kappa:.3f}")
        print(f"  Accuracy: {acc:.3f}  |  Macro P/R/F1: {precision:.3f} / {recall:.3f} / {f1:.3f}")
        print(classification_report(y_true, y_pred, zero_division=0))
        labels = LEVEL_VALUES if col in ORDINAL_COLS else TARGET_VALUES
        cm = confusion_matrix(y_true, y_pred, labels=labels)
        print(f"  Confusion matrix (rows=gold, cols=pred), labels={labels}")
        print(pd.DataFrame(cm, index=labels, columns=labels))

    return results


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main():
    df = load_validation_data()
    gold = df[["_row_id"] + ALL_LABEL_COLS].copy()

    all_results = {}
    predictions_dict = {}

    for model_name, model_tag in OLLAMA_MODELS.items():
        pred = run_model(model_name, model_tag, df)
        predictions_dict[model_name] = build_prediction_lists(pred)
        all_results[model_name] = evaluate(gold, pred, model_name)

    # --- plain dict of lists, e.g. predictions_dict["qwen2.5-7b"][0] == ["low","low","low","none"] ---
    print("\n\n===== PREDICTIONS (dict of lists, order = [hate_speech, negativity, aggressiveness, target]) =====")
    for model_name, lists in predictions_dict.items():
        print(f"\n{model_name}: {len(lists)} speeches")
        for row in lists:
            print(row)

    predictions_json_path = CACHE_DIR / "predictions_dict.json"
    with open(predictions_json_path, "w", encoding="utf-8") as f:
        json.dump(predictions_dict, f, ensure_ascii=False, indent=2)
    print(f"\nPredictions dict saved to {predictions_json_path}")

    # summary table across both models
    summary_rows = []
    for model_name, res in all_results.items():
        for col, metrics in res.items():
            summary_rows.append({"model": model_name, "label": col, **metrics})

    summary_df = pd.DataFrame(summary_rows)
    summary_path = CACHE_DIR / "comparison_summary.csv"
    summary_df.to_csv(summary_path, index=False)

    print("\n\n===== SUMMARY (Mistral vs Qwen) =====")
    print(summary_df.pivot(index="label", columns="model", values="cohen_kappa").round(3))
    print(f"\nFull summary saved to {summary_path}")

    return predictions_dict, all_results


if __name__ == "__main__":
    main()

Loaded 100 validation speeches. Columns: ['politician', 'historical_date', 'location', 'keywords', 'text', 'hate_speech', 'negativity', 'aggressiveness', 'target', 'tags', 'description', 'title', 'url', 'audio_file']

[qwen2.5-7b] 100 cached, 0 to classify.

=== qwen2.5-7b: evaluated on 100/100 speeches ===

--- hate_speech ---
  Cohen's kappa (quadratic-weighted): 0.016
  Accuracy: 0.940  |  Macro P/R/F1: 0.330 / 0.316 / 0.323
              precision    recall  f1-score   support

        high       0.00      0.00      0.00         0
         low       0.99      0.95      0.97        99
         mid       0.00      0.00      0.00         1

    accuracy                           0.94       100
   macro avg       0.33      0.32      0.32       100
weighted avg       0.98      0.94      0.96       100

  Confusion matrix (rows=gold, cols=pred), labels=['low', 'mid', 'high']
      low  mid  high
low    94    0     5
mid     1    0     0
high    0    0     0

--- negativity ---
  Cohen's 

## Qwent VS Mistral Chats

```bash
(crosscode_venv) mhetac@fedora:~/Documents/GitHub/crossdem$ ollama run mistral:7b-instruct-v0.3-q4_K_M
>>> come te la cavi con l'italiano?
 Sono stato creato da un modello di intelligenza artificiale e non posso capire o parlare direttamente. Tuttavia, ho ricevuto il tuo messaggio tradotto in 
inglese: "Can you help me with Italian?"

Potrei fornire aiuti per l'italiano se ti aiuto a tradurre una frase particolare oppure a rispondere alle domande che abbia. Ad esempio, potresti chiedermi 
come si dice "come stai" in italiano, e io posso dirvi che si dice "come stai?"

Se hai bisogno di aiuto con l'italiano, mi piacerebbe essere utile per te.

>>> where you trained in italian also?
 Sì, ho ricevuto un'istruzione specifica sia in inglese che in italiano e posso utilizzare la mia conoscenza dell'italiano per aiutarti a tradurre le frasi 
o rispondere alle domande che abbia.

Ad esempio, potrei fornire aiuti per l'italiano se ti aiuto a tradurre una frase particolare oppure a rispondere alle domande che abbia. Ad esempio, 
potresti chiedermi come si dice "come stai" in italiano, e io posso dirvi che si dice "come stai?"

Se hai bisogno di aiuto con l'italiano, mi piacerebbe essere utile per te.

>>> /bye
(crosscode_venv) mhetac@fedora:~/Documents/GitHub/crossdem$ ollama run qwen2.5:7b-instruct-q4_K_M
>>> come te la cavi con l'italiano?
Ciao! La mia conoscenza linguistica include molte lingue, tra cui l'italiano. Quindi posso comunicare in italiano senza problemi. Come posso aiutarti oggi? 
Hai qualche domanda o的话题已经转向了意大利语交流，我们可以继续用意大利语对话。您需要帮助解答什么问题或讨论什么话题呢？

>>> where you trained in italian also? 
Sì, sono stato addestrato su una vasta gamma di lingue, incluso l'italiano. Posso comunicare e rispondere alle domande in italiano con facilità. Come posso 
aiutarti oggi?

Se hai bisogno di informazioni specifiche o di discutere un determinato argomento in italiano, fammilo sapere!

>>> /bye
```